Repository konstellation-io/kai, pull requests merged in 2023-08, with the labels that each got.

#86 chore: rename all k8s resources
  helm/kai/templates/_helpers.tpl
  helm/kai/templates/engine/admin-api/admin-api-pvc.yaml
  helm/kai/templates/engine/admin-api/configmap.yaml
  helm/kai/templates/engine/admin-api/deployment.yaml
  helm/kai/templates/engine/admin-api/ingress.yaml
  helm/kai/templates/engine/admin-api/secret.yaml
  helm/kai/templates/engine/admin-api/service.yaml
  helm/kai/templates/engine/chronograf/config.yml
  helm/kai/templates/engine/chronograf/deployment.yml
  helm/kai/templates/engine/chronograf/pvc.yml
  helm/kai/templates/engine/chronograf/service.yml
  helm/kai/templates/engine/k8s-manager/configmap.yaml
  helm/kai/templates/engine/k8s-manager/deployment.yaml
  helm/kai/templates/engine/k8s-manager/role.yaml
  helm/kai/templates/engine/k8s-manager/role_binding.yaml
  helm/kai/templates/engine/k8s-manager/service.yaml
  helm/kai/templates/engine/mongo-writer/configmap.yaml
  helm/kai/templates/engine/mongo-writer/deployment.yaml
  helm/kai/templates/engine/nats-manager/configmap.yaml
  helm/kai/templates/engine/nats-manager/deployment.yaml
  helm/kai/templates/engine/nats-manager/service.yaml
  helm/kai/templates/mongo-express/configmap.yaml
  helm/kai/templates/mongo-express/deployment.yml
  helm/kai/templates/mongo-express/service.yaml
  scripts/helmfile/helmfile.lock
Labels: size/m

#87 chore(helm): remove unused stuff
  helm/kai/CHART.md
  helm/kai/templates/engine/admin-api/configmap.yaml
  helm/kai/templates/engine/admin-api/deployment.yaml
  helm/kai/templates/engine/admin-api/secret.yaml
  helm/kai/values.yaml
Labels: size/s

#88 fix(nats-manager): cleanup dots in version tag
  engine/admin-api/go.mod
  engine/admin-api/go.sum
  engine/nats-manager/go.mod
  engine/nats-manager/go.sum
  engine/nats-manager/internal/manager/create_kv_stores_test.go
  engine/nats-manager/internal/manager/create_streams_test.go
  engine/nats-manager/internal/manager/nats.go
Labels: size/m

#91 feat: List process registry query
  engine/admin-api/adapter/gql/generated.go
  engine/admin-api/adapter/gql/resolver.go
  engine/admin-api/adapter/repository/mongodb/processregistry/mapper_test.go
  engine/admin-api/adapter/repository/mongodb/processregistry/process_registry_repository_test.go
  engine/admin-api/adapter/repository/mongodb/processregistry/repository.go
  engine/admin-api/adapter/repository/mongodb/processrepository/entity.go
  engine/admin-api/adapter/repository/mongodb/processrepository/mapper.go
  engine/admin-api/adapter/repository/mongodb/processrepository/mapper_test.go
  engine/admin-api/adapter/repository/mongodb/processrepository/process_repository_test.go
  engine/admin-api/adapter/repository/mongodb/processrepository/repository.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/entity.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/mapper.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/mapper_test.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/repository.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/version_repository_test.go
  engine/admin-api/adapter/service/versionservice/mapper.go
  engine/admin-api/adapter/service/versionservice/start_test.go
  engine/admin-api/adapter/service/versionservice/stop_test.go
  engine/admin-api/adapter/service/versionservice/version_service.go
  engine/admin-api/adapter/service/versionservice/version_service_test.go
  engine/admin-api/domain/entity/registered_process.go
  engine/admin-api/domain/entity/version.go
  engine/admin-api/domain/repository/process_repository.go
  engine/admin-api/domain/service/version.go
  engine/admin-api/domain/usecase/process_service.go
  engine/admin-api/domain/usecase/process_service_test.go
  engine/admin-api/domain/usecase/product_interactor.go
  engine/admin-api/domain/usecase/product_interactor_test.go
  engine/admin-api/domain/usecase/version_dashboards_test.go
  engine/admin-api/domain/usecase/version_interactor.go
  engine/admin-api/domain/usecase/version_interactor_test.go
  engine/admin-api/main.go
  engine/admin-api/mocks/repo_process_registry.go
  engine/admin-api/mocks/repo_process_repository.go
  engine/admin-api/mocks/service_k8s.go
  engine/admin-api/mocks/service_version.go
  engine/admin-api/mocks/version_service.go
  engine/admin-api/schema.graphql
Labels: size/xl
