Repository konstellation-io/kai, pull requests merged in 2023-09, with the labels that each got.

#92 fix(admin-api): Make register process async
  engine/admin-api/adapter/config/viper.go
  engine/admin-api/adapter/gql/generated.go
  engine/admin-api/adapter/gql/models.go
  engine/admin-api/adapter/gql/resolver.go
  engine/admin-api/adapter/repository/mongodb/processrepository/entity.go
  engine/admin-api/adapter/repository/mongodb/processrepository/mapper.go
  engine/admin-api/adapter/repository/mongodb/processrepository/mapper_test.go
  engine/admin-api/adapter/repository/mongodb/processrepository/process_repository_test.go
  engine/admin-api/adapter/repository/mongodb/processrepository/repository.go
  engine/admin-api/adapter/service/proto/versionpb/version.pb.go
  engine/admin-api/adapter/service/versionservice/version_service.go
  engine/admin-api/adapter/service/versionservice/version_service_test.go
  engine/admin-api/domain/entity/registered_process.go
  engine/admin-api/domain/repository/process_repository.go
  engine/admin-api/domain/service/version.go
  engine/admin-api/domain/usecase/process_service.go
  engine/admin-api/domain/usecase/process_service_test.go
  engine/admin-api/gqlgen.yml
  engine/admin-api/mocks/repo_process_repository.go
  engine/admin-api/mocks/service_version.go
  engine/admin-api/schema.graphql
  engine/k8s-manager/internal/application/service/container.go
  engine/k8s-manager/internal/application/usecase/process_register.go
  engine/k8s-manager/internal/application/usecase/process_register_test.go
  engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version.pb.go
  engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version.proto
  engine/k8s-manager/internal/infrastructure/grpc/version.go
  engine/k8s-manager/internal/infrastructure/grpc/version_test.go
  engine/k8s-manager/internal/infrastructure/kube/registry/registry.go
  engine/k8s-manager/internal/infrastructure/kube/registry/registry_test.go
  engine/k8s-manager/mocks/container_service_mock.go
  engine/k8s-manager/mocks/image_builder_mock.go
  helm/kai/templates/engine/admin-api/configmap.yaml
  scripts/helmfile/helmfile.lock
Labels: size/xl

#94 feature(admin-api): create new product from scratch
  engine/admin-api/adapter/gql/resolver.go
  engine/admin-api/adapter/repository/mongodb/processregistry/entity.go
  engine/admin-api/adapter/repository/mongodb/processregistry/mapper.go
  engine/admin-api/adapter/repository/mongodb/processregistry/mapper_test.go
  engine/admin-api/adapter/repository/mongodb/processregistry/process_registry_repository_test.go
  engine/admin-api/adapter/repository/mongodb/processregistry/repository.go
  engine/admin-api/casbin_rbac_policy.csv
  engine/admin-api/domain/entity/process_registry.go
  engine/admin-api/domain/repository/process_registry.go
  engine/admin-api/domain/usecase/product_interactor.go
  engine/admin-api/domain/usecase/product_interactor_test.go
  engine/admin-api/domain/usecase/user_activity.go
  engine/admin-api/domain/usecase/user_activity_test.go
  engine/admin-api/domain/usecase/version_interactor_test.go
  engine/admin-api/main.go
  engine/admin-api/mocks/repo_process_registry.go
Labels: size/xl

#95 feature(ademin-api): Add name and email to user struct
  engine/admin-api/delivery/http/token/claims.go
  engine/admin-api/delivery/http/token/parser.go
  engine/admin-api/domain/entity/user.go
  engine/admin-api/domain/usecase/process_service.go
  engine/admin-api/domain/usecase/process_service_test.go
Labels: size/s

#96 feat (kai): delete helmfile lock
  .gitignore
  scripts/helmfile/helmfile.lock
Labels: size/s

#105 Fix(nats-manager): fix object store name generation
  engine/nats-manager/internal/manager/create_object_store_test.go
  engine/nats-manager/internal/manager/nats.go
Labels: size/s

#107 feature(admin-api): push version
  engine/admin-api/adapter/gql/generated.go
  engine/admin-api/adapter/gql/http_handler.go
  engine/admin-api/adapter/gql/resolver.go
  engine/admin-api/adapter/repository/mongodb/processrepository/repository.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/mapper.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/mapper_test.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/repository.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/version_repository_test.go
  engine/admin-api/adapter/service/chronograf.go
  engine/admin-api/adapter/service/versionservice/version_service.go
  engine/admin-api/domain/entity/version.go
  engine/admin-api/domain/repository/version.go
  engine/admin-api/domain/service/krt/krt_default_values.go
  engine/admin-api/domain/service/krt/krt_mapper.go
  engine/admin-api/domain/service/krt/krt_mapper_test.go
  engine/admin-api/domain/service/krt/krt_parse.go
  engine/admin-api/domain/service/metrics_dashboards.go
  engine/admin-api/domain/usecase/user_activity.go
  engine/admin-api/domain/usecase/version/create.go
  engine/admin-api/domain/usecase/version/create_test.go
  engine/admin-api/domain/usecase/version/errors.go
  engine/admin-api/domain/usecase/version/handler.go
  engine/admin-api/domain/usecase/version/handler_test.go
  engine/admin-api/domain/usecase/version/krt_mapper.go
  engine/admin-api/domain/usecase/version/suite_test.go
  engine/admin-api/domain/usecase/version/testdata/classificator_krt.yaml
  engine/admin-api/domain/usecase/version/testdata/dashboards/models.json
  engine/admin-api/domain/usecase/version/version_dashboards.go
  engine/admin-api/domain/usecase/version/version_dashboards_test.go
  engine/admin-api/internal/errors/errors.go
  engine/admin-api/main.go
  engine/admin-api/mocks/repo_version.go
  engine/admin-api/mocks/usecase_user_activity.go
  engine/admin-api/schema.graphql
  engine/admin-api/testhelpers/process_builder.go
  engine/admin-api/testhelpers/workflow_builder.go
Labels: size/xl

#99 Feature/start version
  engine/admin-api/.golangci.yml
  engine/admin-api/adapter/gql/generated.go
  engine/admin-api/adapter/gql/resolver.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/entity.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/mapper.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/repository.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/version_repository_test.go
  engine/admin-api/adapter/service/natsmanager/nats_manager_test.go
  engine/admin-api/adapter/service/proto/natspb/nats.pb.go
  engine/admin-api/adapter/service/proto/natspb/nats_grpc.pb.go
  engine/admin-api/adapter/service/proto/versionpb/version.pb.go
  engine/admin-api/adapter/service/proto/versionpb/version_grpc.pb.go
  engine/admin-api/adapter/service/versionservice/start_test.go
  engine/admin-api/adapter/service/versionservice/stop_test.go
  engine/admin-api/adapter/service/versionservice/version_service_test.go
  engine/admin-api/domain/entity/version.go
  engine/admin-api/domain/repository/version.go
  engine/admin-api/domain/usecase/user_activity_test.go
  engine/admin-api/domain/usecase/version/errors.go
  engine/admin-api/domain/usecase/version/get_by_id_test.go
  engine/admin-api/domain/usecase/version/get_by_tag_test.go
  engine/admin-api/domain/usecase/version/list_by_product_test.go
  engine/admin-api/domain/usecase/version/start.go
  engine/admin-api/domain/usecase/version/start_test.go
  engine/admin-api/internal/errors/errors.go
  engine/admin-api/mocks/repo_version.go
  engine/admin-api/schema.graphql
  engine/admin-api/testhelpers/version_builder.go
  engine/k8s-manager/internal/infrastructure/kube/configuration/create.go
  engine/k8s-manager/internal/infrastructure/kube/configuration/testdata/ConfigMapCreation.golden
  engine/k8s-manager/internal/infrastructure/kube/network/create.go
  engine/k8s-manager/internal/infrastructure/kube/network/testdata/CreateNetwork.golden
  engine/k8s-manager/internal/infrastructure/kube/process/create.go
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithCPU.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithEnableGpu.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithMoreReplicas.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithNetworking.golden
Labels: size/l

#110 fix(admin-api): fix set status search parameters
  engine/admin-api/domain/repository/version.go
  engine/admin-api/domain/usecase/version/start.go
  engine/admin-api/domain/usecase/version/start_test.go
  engine/admin-api/mocks/repo_version.go
Labels: size/s

#108 feat(helm): add MinIO
  helm/kai/CHART.md
  helm/kai/Chart.lock
  helm/kai/Chart.yaml
  helm/kai/values.yaml
  scripts/helmfile/values/kai-local/values.yaml.gotmpl
  scripts/kaictl/cmd_etchost.sh
Labels: size/s

#111 chore(helm): configure minio pods default resources
  helm/kai/values.yaml
Labels: size/xs

#113 Feature/get version info
  engine/admin-api/adapter/gql/generated.go
  engine/admin-api/adapter/gql/resolver.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/entity.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/mapper.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/mapper_test.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/repository.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/version_repository_test.go
  engine/admin-api/domain/entity/product.go
  engine/admin-api/domain/entity/version.go
  engine/admin-api/domain/repository/version.go
  engine/admin-api/domain/usecase/user_activity.go
  engine/admin-api/domain/usecase/user_activity_test.go
  engine/admin-api/domain/usecase/version/get_by_id.go
  engine/admin-api/domain/usecase/version/get_by_id_test.go
  engine/admin-api/domain/usecase/version/list_by_product_test.go
  engine/admin-api/domain/usecase/version/publish.go
  engine/admin-api/domain/usecase/version/start_test.go
  engine/admin-api/domain/usecase/version/stop_test.go
  engine/admin-api/domain/usecase/version/suite_test.go
  engine/admin-api/gqlgen.yml
  engine/admin-api/mocks/repo_version.go
  engine/admin-api/mocks/usecase_user_activity.go
  engine/admin-api/schema.graphql
  engine/admin-api/testhelpers/version_builder.go
Labels: size/m

#115 feature: publish version
  engine/admin-api/adapter/gql/generated.go
  engine/admin-api/adapter/gql/models.go
  engine/admin-api/adapter/gql/resolver.go
  engine/admin-api/adapter/service/proto/versionpb/version.pb.go
  engine/admin-api/adapter/service/proto/versionpb/version_grpc.pb.go
  engine/admin-api/adapter/service/versionservice/version_service.go
  engine/admin-api/adapter/service/versionservice/version_service_test.go
  engine/admin-api/domain/service/version.go
  engine/admin-api/domain/usecase/version/errors.go
  engine/admin-api/domain/usecase/version/publish.go
  engine/admin-api/domain/usecase/version/publish_test.go
  engine/admin-api/internal/errors/errors.go
  engine/admin-api/mocks/service_version.go
  engine/admin-api/mocks/version_service.go
  engine/admin-api/schema.graphql
  engine/admin-api/sonar-project.properties
  engine/admin-api/testhelpers/token_builder.go
  engine/admin-api/testhelpers/user_builder.go
  engine/k8s-manager/cmd/bootstrap/bootstrap.go
  engine/k8s-manager/internal/application/service/container.go
  engine/k8s-manager/internal/application/usecase/interfaces.go
  engine/k8s-manager/internal/application/usecase/publisher.go
  engine/k8s-manager/internal/application/usecase/publisher_test.go
  engine/k8s-manager/internal/infrastructure/config/viper.go
  engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version.pb.go
  engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version.proto
  engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version_grpc.pb.go
  engine/k8s-manager/internal/infrastructure/grpc/version.go
  engine/k8s-manager/internal/infrastructure/grpc/version_test.go
  engine/k8s-manager/internal/infrastructure/kube/network/create.go
  engine/k8s-manager/internal/infrastructure/kube/network/network_test.go
  engine/k8s-manager/internal/infrastructure/kube/network/publish.go
  engine/k8s-manager/internal/infrastructure/kube/network/publish_test.go
  engine/k8s-manager/internal/infrastructure/kube/network/testdata/CreateNetwork.golden
  engine/k8s-manager/internal/infrastructure/kube/network/testdata/PublishNetwork.golden
  engine/k8s-manager/internal/infrastructure/kube/network/testdata/PublishNetwork_WithTLS.golden
  engine/k8s-manager/internal/infrastructure/kube/network/testdata/PublishNetwork_WithTLS_WithTLSSecret.golden
  engine/k8s-manager/internal/infrastructure/kube/service.go
  engine/k8s-manager/mocks/container_service_mock.go
  engine/k8s-manager/mocks/image_builder_mock.go
  engine/k8s-manager/mocks/version_service_mock.go
  scripts/helmfile/helmfile.yaml
Labels: size/xl

#114 Feature/unpublish refactor
  engine/admin-api/adapter/service/proto/versionpb/version.pb.go
  engine/admin-api/adapter/service/proto/versionpb/version_grpc.pb.go
  engine/admin-api/domain/usecase/version/create.go
  engine/admin-api/domain/usecase/version/errors.go
  engine/admin-api/domain/usecase/version/publish_test.go
  engine/admin-api/domain/usecase/version/start.go
  engine/admin-api/domain/usecase/version/start_test.go
  engine/admin-api/domain/usecase/version/stop.go
  engine/admin-api/domain/usecase/version/stop_test.go
  engine/admin-api/domain/usecase/version/suite_test.go
  engine/admin-api/domain/usecase/version/unpublish.go
  engine/admin-api/domain/usecase/version/unpublish_test.go
  engine/admin-api/internal/errors/errors.go
  engine/k8s-manager/cmd/bootstrap/bootstrap.go
  engine/k8s-manager/internal/application/service/container.go
  engine/k8s-manager/internal/application/usecase/interfaces.go
  engine/k8s-manager/internal/application/usecase/publisher.go
  engine/k8s-manager/internal/application/usecase/unpublisher.go
  engine/k8s-manager/internal/application/usecase/unpublisher_test.go
  engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version.pb.go
  engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version_grpc.pb.go
  engine/k8s-manager/internal/infrastructure/grpc/version.go
  engine/k8s-manager/internal/infrastructure/grpc/version_test.go
  engine/k8s-manager/internal/infrastructure/kube/configuration/create_test.go
  engine/k8s-manager/internal/infrastructure/kube/configuration/delete_test.go
  engine/k8s-manager/internal/infrastructure/kube/network/network_test.go
  engine/k8s-manager/internal/infrastructure/kube/network/publish_test.go
  engine/k8s-manager/internal/infrastructure/kube/network/suite_test.go
  engine/k8s-manager/internal/infrastructure/kube/network/unpublish.go
  engine/k8s-manager/internal/infrastructure/kube/network/unpublish_test.go
  engine/k8s-manager/internal/infrastructure/kube/process/create_test.go
  engine/k8s-manager/internal/infrastructure/kube/process/delete_test.go
  engine/k8s-manager/internal/infrastructure/kube/service.go
  engine/k8s-manager/mocks/container_service_mock.go
  engine/k8s-manager/mocks/image_builder_mock.go
  engine/k8s-manager/mocks/process_service_mock.go
  engine/k8s-manager/mocks/version_service_mock.go
Labels: size/l

#116 fix(helm): publish registry using ingress
  .kaictl.conf
  README.md
  helm/kai/templates/_helpers.tpl
  helm/kai/templates/engine/admin-api/registry-auth-secret.yaml
  helm/kai/templates/engine/k8s-manager/configmap.yaml
  helm/kai/templates/engine/registry/config-secret.yaml
  helm/kai/templates/engine/registry/deployment.yaml
  helm/kai/templates/engine/registry/htpasswd-secret.yaml
  helm/kai/templates/engine/registry/ingress.yaml
  helm/kai/templates/engine/registry/registry-auth-secret.yaml
  helm/kai/templates/engine/registry/secret.yaml
  helm/kai/values.yaml
  scripts/kaictl/cmd_etchost.sh
  scripts/kaictl/cmd_minikube.sh
Labels: size/m

#118 fix(helm): remove unused secret
  helm/kai/templates/engine/admin-api/registry-auth-secret.yaml
Labels: size/s

#120 fix: upload and pull image via ingress
  engine/admin-api/adapter/config/viper.go
  engine/admin-api/domain/usecase/process_service.go
  engine/admin-api/domain/usecase/process_service_test.go
  engine/k8s-manager/internal/infrastructure/config/viper.go
  engine/k8s-manager/internal/infrastructure/kube/process/create.go
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithCPU.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithEnableGpu.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithMoreReplicas.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithNetworking.golden
  engine/k8s-manager/internal/infrastructure/kube/registry/registry.go
  engine/k8s-manager/internal/infrastructure/kube/registry/testdata/BuildImage_Job.golden
  helm/kai/templates/engine/admin-api/configmap.yaml
  helm/kai/templates/engine/k8s-manager/configmap.yaml
Labels: size/m

#121 feat(helm): pass S3 credentials to the API
  helm/kai/CHART.md
  helm/kai/templates/engine/admin-api/configmap.yaml
  helm/kai/templates/engine/admin-api/deployment.yaml
  helm/kai/templates/engine/admin-api/secret.yaml
  helm/kai/templates/engine/keycloak/ingress.yaml
  helm/kai/values.yaml
  scripts/helmfile/values/kai-local/values.yaml.gotmpl
Labels: size/s

#123 fix(helm): pass AWS_REGION to Admin API
  helm/kai/CHART.md
  helm/kai/templates/_helpers.tpl
  helm/kai/templates/engine/admin-api/configmap.yaml
  helm/kai/values.yaml
Labels: size/s

#124 fix: Kaniko insecure registry flag
  engine/k8s-manager/internal/infrastructure/config/viper.go
  engine/k8s-manager/internal/infrastructure/kube/registry/registry.go
  engine/k8s-manager/internal/infrastructure/kube/registry/testdata/BuildImage_Job.golden
  helm/kai/templates/engine/k8s-manager/configmap.yaml
Labels: size/xs

#125 fix: make registry protocol configurable
  helm/kai/templates/engine/registry/registry-auth-secret.yaml
Labels: size/xs
