Repository konstellation-io/kai, pull requests merged in 2023-05, with the labels that each got.

#15 Fix PR Size Labeler
  .github/workflows/utils-pr-size-labeler.yaml
  docs/technical_specifications/branching_strategy.md
Labels: size/xs

#16 Add CI workflows
  .github/workflows/test-admin-api.yaml
  .github/workflows/test-k8s-manager.yaml
  .github/workflows/test-mongo-writer.yaml
  .github/workflows/test-nats-manager.yaml
  engine/admin-api/sonar-project.properties
  engine/k8s-manager/sonar-project.properties
  engine/mongo-writer/sonar-project.properties
  engine/nats-manager/sonar-project.properties
Labels: size/m

#17 ci: execute unit tests on push events
  .github/workflows/test-admin-api.yaml
  .github/workflows/test-k8s-manager.yaml
  .github/workflows/test-mongo-writer.yaml
  .github/workflows/test-nats-manager.yaml
Labels: size/s

#18 ci: fix typo in test-k8s-manager.yaml
  .github/workflows/test-k8s-manager.yaml
Labels: size/s

#26 Update go version
  engine/admin-api/Dockerfile
  engine/admin-api/go.mod
  engine/k8s-manager/Dockerfile
  engine/k8s-manager/go.mod
  engine/mongo-writer/Dockerfile
  engine/mongo-writer/go.mod
  engine/nats-manager/Dockerfile
  engine/nats-manager/go.mod
  go.work
  go.work.sum
  libs/krt-utils/go.mod
  libs/simplelogger/go.mod
  scripts/go_tidy_modules.sh
  tests/acceptance/.golangci.yml
  tests/acceptance/README.md
  tests/acceptance/config/config.go
  tests/acceptance/entity/version.go
  tests/acceptance/features/Runtime_Version_Management.feature
  tests/acceptance/features/Settings.feature
  tests/acceptance/go.mod
  tests/acceptance/go.sum
  tests/acceptance/graphql/auth.go
  tests/acceptance/graphql/graphql.go
  tests/acceptance/graphql/mutation_update_session_lifetime.go
  tests/acceptance/graphql/mutation_version_publishing.go
  tests/acceptance/graphql/query_settings_session_lifetime.go
  tests/acceptance/graphql/query_version.go
  tests/acceptance/login.go
  tests/acceptance/main_test.go
  tests/acceptance/pb/public_input.pb.go
  tests/acceptance/pb/public_input_grpc.pb.go
  tests/acceptance/runner.go
  tests/acceptance/scripts/gen_protobuf.sh
  tests/acceptance/settings_feature.go
  tests/acceptance/test_krt/.gitignore
  tests/acceptance/test_krt/README.md
  tests/acceptance/test_krt/runtime-test-v1/bin/.gitkeep
  tests/acceptance/test_krt/runtime-test-v1/krt.yml
  tests/acceptance/test_krt/runtime-test-v1/public_input.proto
  tests/acceptance/test_krt/runtime-test-v1/src/go-runner/go.mod
  tests/acceptance/test_krt/runtime-test-v1/src/go-runner/go.sum
  tests/acceptance/test_krt/runtime-test-v1/src/go-runner/main.go
  tests/acceptance/test_krt/runtime-test-v1/src/go-runner/pb/public_input.pb.go
  tests/acceptance/test_krt/runtime-test-v1/src/py-runner/main.py
  tests/acceptance/test_krt/runtime-test-v1/src/py-runner/public_input_pb2.py
  tests/acceptance/test_krt/scripts/build_krt.sh
  tests/acceptance/test_krt/scripts/gen_protobuf.sh
  tests/acceptance/test_krt/scripts/local_test.sh
  tests/acceptance/version_feature.go
Labels: size/xl

#27 refactor(admin-api): fix editorconfig file selector
  engine/admin-api/.editorconfig
Labels: size/xs

#35 feat(admin-api): new gocloak client, updated user usecase
  engine/admin-api/adapter/auth/casbin_access_control.go
  engine/admin-api/adapter/config/config.go
  engine/admin-api/adapter/gql/generated.go
  engine/admin-api/adapter/gql/models.go
  engine/admin-api/adapter/gql/resolver.go
  engine/admin-api/adapter/service/gocloak.go
  engine/admin-api/domain/entity/runtime.go
  engine/admin-api/domain/entity/user.go
  engine/admin-api/domain/entity/user_activity.go
  engine/admin-api/domain/service/user_registry.go
  engine/admin-api/domain/usecase/auth/access_control.go
  engine/admin-api/domain/usecase/metrics.go
  engine/admin-api/domain/usecase/runtime_interactor.go
  engine/admin-api/domain/usecase/runtime_interactor_test.go
  engine/admin-api/domain/usecase/user.go
  engine/admin-api/domain/usecase/user_activity.go
  engine/admin-api/domain/usecase/user_activity_test.go
  engine/admin-api/domain/usecase/user_test.go
  engine/admin-api/domain/usecase/version_interactor.go
  engine/admin-api/domain/usecase/version_interactor_test.go
  engine/admin-api/go.mod
  engine/admin-api/go.sum
  engine/admin-api/internal/errors/errors.go
  engine/admin-api/main.go
  engine/admin-api/mocks/auth_access_control.go
  engine/admin-api/mocks/service_metrics_dashboards.go
  engine/admin-api/mocks/service_nats.go
  engine/admin-api/mocks/service_user_registry.go
  engine/admin-api/mocks/service_version.go
  engine/admin-api/mocks/usecase_user_activity.go
  engine/admin-api/schema.graphql
  engine/k8s-manager/kubernetes/watcher.go
Labels: size/xl

#39 KNT1-338 rename k9s-manager's runtime references to product and delet…
  .editorconfig
  engine/admin-api/adapter/service/proto/versionpb/version.pb.go
  engine/admin-api/adapter/service/proto/versionpb/version_grpc.pb.go
  engine/admin-api/adapter/service/version.go
  engine/k8s-manager/README.md
  engine/k8s-manager/assets/role.yaml
  engine/k8s-manager/assets/role_binding.yaml
  engine/k8s-manager/assets/service_account.yaml
  engine/k8s-manager/config.yml
  engine/k8s-manager/config/config.go
  engine/k8s-manager/go.mod
  engine/k8s-manager/go.sum
  engine/k8s-manager/kubernetes/version/config.go
  engine/k8s-manager/kubernetes/version/entrypoint.go
  engine/k8s-manager/kubernetes/version/ingress.go
  engine/k8s-manager/kubernetes/version/manager.go
  engine/k8s-manager/kubernetes/version/manager_node.go
  engine/k8s-manager/kubernetes/version/volumes.go
  engine/k8s-manager/kubernetes/watcher.go
  engine/k8s-manager/proto/versionpb/version.pb.go
  engine/k8s-manager/proto/versionpb/version.proto
  engine/k8s-manager/proto/versionpb/version_grpc.pb.go
  engine/k8s-manager/service/version.go
  scripts/helmfile/helmfile.lock
Labels: size/l

#44 fix(k8s-manager): delete unused code and fix Dockerfile
  engine/k8s-manager/Dockerfile
  engine/k8s-manager/kubernetes/client.go
  engine/k8s-manager/kubernetes/version/manager.go
  engine/k8s-manager/kubernetes/version/manager_node.go
  engine/k8s-manager/kubernetes/watcher.go
Labels: size/s

#43 feat(nats-manager): separate unit and integration tests
  .github/workflows/test-nats-manager.yaml
  engine/nats-manager/internal/manager/nats_test.go
  engine/nats-manager/internal/manager/workflow_builder_test.go
  engine/nats-manager/nats/client_integration_test.go
  engine/nats-manager/sonar-project.properties
Labels: size/s

#41 feat(k8s manager): separate unit and integration testing
  .github/workflows/test-k8s-manager.yaml
Labels: size/s

#50 feat(k8s-manager): update go mod
  engine/k8s-manager/go.mod
  engine/k8s-manager/go.sum
Labels: size/xs

#53 fix(admin-api): set user struct to context
  engine/admin-api/delivery/http/controller/graphql.go
Labels: size/xs
