Repository konstellation-io/kai, pull requests merged in 2023-11, with the labels that each got.

#165 feature: upload images minio
  engine/admin-api/adapter/repository/objectstorage/minio.go
  engine/admin-api/adapter/repository/objectstorage/minio_test.go
  engine/admin-api/adapter/service/proto/versionpb/version.pb.go
  engine/admin-api/adapter/service/versionservice/version_service.go
  engine/admin-api/adapter/service/versionservice/version_service_test.go
  engine/admin-api/domain/repository/object_storage.go
  engine/admin-api/domain/service/version.go
  engine/admin-api/domain/usecase/process_service.go
  engine/admin-api/domain/usecase/process_service_test.go
  engine/admin-api/main.go
  engine/admin-api/mocks/object_storage.go
  engine/admin-api/mocks/service_version.go
  engine/k8s-manager/internal/application/service/container.go
  engine/k8s-manager/internal/application/usecase/process_register.go
  engine/k8s-manager/internal/application/usecase/process_register_test.go
  engine/k8s-manager/internal/infrastructure/config/viper.go
  engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version.pb.go
  engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version.proto
  engine/k8s-manager/internal/infrastructure/grpc/version.go
  engine/k8s-manager/internal/infrastructure/grpc/version_test.go
  engine/k8s-manager/internal/infrastructure/kube/registry/registry.go
  engine/k8s-manager/internal/infrastructure/kube/registry/registry_test.go
  engine/k8s-manager/internal/infrastructure/kube/registry/testdata/BuildImage.golden
  engine/k8s-manager/internal/infrastructure/kube/registry/testdata/BuildImage_ConfigMap.golden
  engine/k8s-manager/internal/infrastructure/kube/registry/testdata/BuildImage_Job.golden
  engine/k8s-manager/mocks/container_service_mock.go
  engine/k8s-manager/mocks/image_builder_mock.go
  engine/k8s-manager/mocks/process_service_mock.go
  engine/k8s-manager/mocks/version_service_mock.go
  helm/kai/templates/engine/k8s-manager/configmap.yaml
  helm/kai/templates/engine/k8s-manager/deployment.yaml
Labels: size/xl

#168 feat: add roles and groups for admins and regular users
  helm/kai/templates/engine/keycloak/minio-client-config-job.yaml
  helm/kai/templates/engine/keycloak/realm-init-secret.yaml
  scripts/kaictl/cmd_deploy.sh
Labels: size/m

#170 fix: refactor start version method
  engine/admin-api/adapter/gql/resolver.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/repository.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/version_repository_test.go
  engine/admin-api/casbin_rbac_policy.csv
  engine/admin-api/domain/entity/version.go
  engine/admin-api/domain/repository/version.go
  engine/admin-api/domain/service/auth/access_control.go
  engine/admin-api/domain/usecase/version/errors.go
  engine/admin-api/domain/usecase/version/start.go
  engine/admin-api/domain/usecase/version/start_test.go
  engine/admin-api/domain/usecase/version/stop.go
  engine/admin-api/domain/usecase/version/stop_test.go
  engine/admin-api/domain/usecase/version/suite_test.go
  engine/admin-api/mocks/repo_version.go
  engine/admin-api/pkg/compensator/compensator.go
  engine/admin-api/testhelpers/utils.go
  engine/k8s-manager/internal/application/service/container.go
  engine/k8s-manager/internal/application/usecase/starter.go
  engine/k8s-manager/internal/application/usecase/starter_test.go
  engine/k8s-manager/internal/infrastructure/config/viper.go
  engine/k8s-manager/internal/infrastructure/kube/process/wait_processes.go
  engine/k8s-manager/internal/infrastructure/kube/process/wait_processes_test.go
  engine/k8s-manager/internal/infrastructure/kube/service.go
  engine/k8s-manager/mocks/container_service_mock.go
  engine/k8s-manager/pkg/compensator/compensator.go
Labels: size/xl

#172 feature(engine): add protocol annotations to services
  engine/admin-api/adapter/repository/mongodb/versionrepository/mapper.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/mapper_test.go
  engine/admin-api/adapter/service/natsmanager/nats_manager_test.go
  engine/admin-api/adapter/service/versionservice/mapper.go
  engine/admin-api/adapter/service/versionservice/start_test.go
  engine/admin-api/domain/entity/version.go
  engine/admin-api/domain/usecase/version/create_test.go
  engine/admin-api/domain/usecase/version/krt_mapper.go
  engine/admin-api/domain/usecase/version/testdata/classificator_krt.yaml
  engine/admin-api/go.mod
  engine/admin-api/go.sum
  engine/k8s-manager/.golangci.yml
  engine/k8s-manager/internal/application/usecase/starter_test.go
  engine/k8s-manager/internal/domain/process.go
  engine/k8s-manager/internal/infrastructure/grpc/mapper.go
  engine/k8s-manager/internal/infrastructure/grpc/version_test.go
  engine/k8s-manager/internal/infrastructure/kube/network/create.go
  engine/k8s-manager/internal/infrastructure/kube/network/network_test.go
  engine/k8s-manager/internal/infrastructure/kube/network/publish_test.go
  engine/k8s-manager/internal/infrastructure/kube/network/testdata/CreateNetwork.golden
  engine/k8s-manager/internal/infrastructure/kube/network/unpublish_test.go
  engine/k8s-manager/internal/infrastructure/kube/process/containers.go
  engine/k8s-manager/internal/infrastructure/kube/process/create_test.go
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithNetworking.golden
  helm/kai/templates/engine/k8s-manager/configmap.yaml
Labels: size/m

#171 feature: share minio credentials and access properties from kai to the processes
  engine/admin-api/adapter/service/proto/versionpb/version.pb.go
  engine/admin-api/adapter/service/versionservice/start_test.go
  engine/admin-api/adapter/service/versionservice/version_service.go
  engine/admin-api/domain/entity/product.go
  engine/admin-api/domain/service/version.go
  engine/admin-api/domain/usecase/product_interactor.go
  engine/admin-api/domain/usecase/product_interactor_test.go
  engine/admin-api/domain/usecase/version/start.go
  engine/admin-api/domain/usecase/version/start_test.go
  engine/admin-api/mocks/service_version.go
  engine/admin-api/testhelpers/product_builder.go
  engine/k8s-manager/internal/domain/version.go
  engine/k8s-manager/internal/infrastructure/config/viper.go
  engine/k8s-manager/internal/infrastructure/grpc/mapper.go
  engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version.pb.go
  engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version.proto
  engine/k8s-manager/internal/infrastructure/grpc/version_test.go
  engine/k8s-manager/internal/infrastructure/kube/configuration/create.go
  engine/k8s-manager/internal/infrastructure/kube/configuration/create_test.go
  engine/k8s-manager/internal/infrastructure/kube/configuration/testdata/ConfigMapCreation.golden
  engine/k8s-manager/internal/infrastructure/kube/configuration/types.go
  engine/k8s-manager/internal/testhelpers/version_builder.go
  helm/kai/templates/engine/k8s-manager/configmap.yaml
  helm/kai/templates/engine/k8s-manager/deployment.yaml
Labels: size/xl

#175 fix(admin-api): enable versioning in generated minio buckets
  engine/admin-api/adapter/repository/objectstorage/minio.go
Labels: size/xs

#174 feat(helm): refactor loki-stack and include prometheus
  helm/kai/CHART.md
  helm/kai/Chart.lock
  helm/kai/Chart.yaml
  helm/kai/templates/_helpers.tpl
  helm/kai/templates/engine/admin-api/configmap.yaml
  helm/kai/templates/engine/grafana/datasources-configmap.yaml
  helm/kai/values.yaml
  scripts/kaictl/cmd_etchost.sh
Labels: size/m

#178 feat(helm): add redis
  helm/kai/Chart.lock
  helm/kai/Chart.yaml
  helm/kai/templates/_helpers.tpl
  helm/kai/templates/engine/admin-api/configmap.yaml
  helm/kai/values.yaml
Labels: size/m

#176 Feature/add prometheus
  helm/kai/CHART.md
  helm/kai/values.yaml
Labels: size/s

#181 chore: make Grafana, Loki and Prometheus outsourceable
  helm/kai/CHART.md
  helm/kai/templates/_helpers.tpl
  helm/kai/templates/engine/admin-api/configmap.yaml
  helm/kai/templates/engine/grafana/datasources-configmap.yaml
  helm/kai/values.yaml
Labels: size/m

#182 fix(k8s-manager): add fluentbit env vars
  engine/k8s-manager/internal/infrastructure/config/viper.go
  engine/k8s-manager/internal/infrastructure/kube/process/containers.go
  engine/k8s-manager/internal/infrastructure/kube/process/create_test.go
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithCPU.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithEnableGpu.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithHPA_Deployment.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithMoreReplicas.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithNetworking.golden
Labels: size/s

#179 fix(admin-api): bucket policy
  engine/admin-api/adapter/repository/objectstorage/minio.go
  engine/admin-api/adapter/repository/objectstorage/testdata/CreateBucketPolicy.golden
Labels: size/xs

#183 feat(helm): make redis optional
  helm/kai/CHART.md
  helm/kai/templates/_helpers.tpl
  helm/kai/templates/engine/admin-api/configmap.yaml
  helm/kai/templates/engine/admin-api/deployment.yaml
  helm/kai/templates/engine/redis/redis-secret.yaml
  helm/kai/values.yaml
Labels: size/m

#177 Feature(nats-manager): delete version key value stores
  engine/admin-api/adapter/service/natsmanager/nats_manager.go
  engine/admin-api/adapter/service/natsmanager/nats_manager_test.go
  engine/admin-api/adapter/service/proto/natspb/nats.pb.go
  engine/admin-api/adapter/service/proto/natspb/nats_grpc.pb.go
  engine/admin-api/domain/service/nats.go
  engine/admin-api/domain/usecase/version/start.go
  engine/admin-api/domain/usecase/version/start_test.go
  engine/admin-api/domain/usecase/version/stop.go
  engine/admin-api/domain/usecase/version/stop_test.go
  engine/admin-api/mocks/nats_manager.go
  engine/admin-api/mocks/service_nats.go
  engine/nats-manager/internal/interfaces/nats_client.go
  engine/nats-manager/internal/interfaces/nats_manager.go
  engine/nats-manager/internal/manager/create_kv_stores.go
  engine/nats-manager/internal/manager/create_kv_stores_test.go
  engine/nats-manager/internal/manager/delete_kv_stores.go
  engine/nats-manager/internal/manager/delete_kv_stores_test.go
  engine/nats-manager/internal/service/nats.go
  engine/nats-manager/internal/service/nats_test.go
  engine/nats-manager/mocks/nats_client.go
  engine/nats-manager/mocks/nats_manager.go
  engine/nats-manager/nats/client.go
  engine/nats-manager/nats/client_integration_test.go
  engine/nats-manager/proto/natspb/nats.pb.go
  engine/nats-manager/proto/natspb/nats.proto
  engine/nats-manager/proto/natspb/nats_grpc.pb.go
Labels: size/xl

#186 fix: minio configuration
  engine/admin-api/adapter/repository/objectstorage/minio.go
  engine/k8s-manager/internal/infrastructure/kube/configuration/testdata/ConfigMapCreation.golden
  engine/k8s-manager/internal/infrastructure/kube/configuration/types.go
  helm/kai/templates/engine/k8s-manager/deployment.yaml
Labels: size/s

#184 feat(helm): add fluent bit and telegraf sidecar images config
  engine/k8s-manager/internal/infrastructure/config/viper.go
  engine/k8s-manager/internal/infrastructure/kube/configuration/configmap.go
  engine/k8s-manager/internal/infrastructure/kube/configuration/testdata/ConfigMapCreation.golden
  helm/kai/CHART.md
  helm/kai/templates/engine/k8s-manager/configmap.yaml
  helm/kai/values.yaml
Labels: size/m

#180 fix: delete version in hosts urls when a version is published
  engine/admin-api/adapter/config/viper.go
  engine/admin-api/adapter/repository/mongodb/product.go
  engine/admin-api/adapter/repository/mongodb/product_test.go
  engine/admin-api/domain/entity/product.go
  engine/admin-api/domain/entity/product_test.go
  engine/admin-api/domain/entity/version.go
  engine/admin-api/domain/entity/version_test.go
  engine/admin-api/domain/repository/product.go
  engine/admin-api/domain/usecase/version/create_test.go
  engine/admin-api/domain/usecase/version/publish.go
  engine/admin-api/domain/usecase/version/publish_test.go
  engine/admin-api/main.go
  engine/admin-api/mocks/repo_product.go
  engine/admin-api/testhelpers/product_builder.go
  engine/admin-api/testhelpers/utils.go
  engine/k8s-manager/internal/infrastructure/kube/network/publish.go
  engine/k8s-manager/internal/infrastructure/kube/network/publish_test.go
  engine/k8s-manager/internal/infrastructure/kube/network/testdata/PublishNetwork.golden
  engine/k8s-manager/internal/infrastructure/kube/network/testdata/PublishNetwork_GRPCTrigger.golden
  engine/k8s-manager/internal/infrastructure/kube/network/testdata/PublishNetwork_WithTLS.golden
  engine/k8s-manager/internal/infrastructure/kube/network/testdata/PublishNetwork_WithTLS_WithTLSSecret.golden
Labels: size/l

#189 fix(k8s-manager): update kubernetes client-go to 0.27.8
  engine/k8s-manager/go.mod
  engine/k8s-manager/go.sum
  engine/k8s-manager/internal/infrastructure/kube/configuration/testdata/ConfigMapCreation.golden
  engine/k8s-manager/internal/infrastructure/kube/network/testdata/CreateNetwork.golden
  engine/k8s-manager/internal/infrastructure/kube/network/testdata/PublishNetwork.golden
  engine/k8s-manager/internal/infrastructure/kube/network/testdata/PublishNetwork_GRPCTrigger.golden
  engine/k8s-manager/internal/infrastructure/kube/network/testdata/PublishNetwork_WithTLS.golden
  engine/k8s-manager/internal/infrastructure/kube/network/testdata/PublishNetwork_WithTLS_WithTLSSecret.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithCPU.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithEnableGpu.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithHPA_Deployment.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithHPA_HPA.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithMoreReplicas.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithNetworking.golden
  engine/k8s-manager/internal/infrastructure/kube/registry/testdata/BuildImage_Job.golden
Labels: size/m

#188 chore(helm): add the posibility to change RollingUpdate strategy
  helm/kai/CHART.md
  helm/kai/templates/engine/registry/deployment.yaml
  helm/kai/values.yaml
Labels: size/s

#187 feat(scripts): update local pg operator chart version in local deploys
  scripts/helmfile/helmfile.yaml
Labels: size/xs

#190 fix(admin-api): delete legacy repositories
  engine/admin-api/adapter/config/config.go
  engine/admin-api/adapter/gql/generated.go
  engine/admin-api/adapter/gql/http_handler.go
  engine/admin-api/adapter/gql/resolver.go
  engine/admin-api/adapter/repository/influx/measurement.go
  engine/admin-api/adapter/repository/mongodb/metrics.go
  engine/admin-api/adapter/repository/mongodb/processlog.go
  engine/admin-api/config.yml
  engine/admin-api/delivery/http/controller/graphql.go
  engine/admin-api/delivery/http/middleware/chronograf_proxy.go
  engine/admin-api/delivery/http/middleware/mongoexpress_proxy.go
  engine/admin-api/delivery/http/middleware/reverse_proxy.go
  engine/admin-api/delivery/http/server.go
  engine/admin-api/domain/repository/measurement.go
  engine/admin-api/domain/repository/metric.go
  engine/admin-api/domain/repository/processlog.go
  engine/admin-api/domain/usecase/metrics.go
  engine/admin-api/domain/usecase/metrics_test.go
  engine/admin-api/domain/usecase/product_interactor.go
  engine/admin-api/domain/usecase/product_interactor_test.go
  engine/admin-api/domain/usecase/version/handler.go
  engine/admin-api/domain/usecase/version/search_logs.go
  engine/admin-api/domain/usecase/version/suite_test.go
  engine/admin-api/domain/usecase/version/watch_process_logs.go
  engine/admin-api/gqlgen.yml
  engine/admin-api/main.go
  engine/admin-api/mocks/repo_measurement.go
  engine/admin-api/mocks/repo_metric.go
  engine/admin-api/mocks/repo_processlog.go
  engine/admin-api/mocks/service_metrics_dashboards.go
  engine/admin-api/schema.graphql
  helm/kai/templates/engine/admin-api/configmap.yaml
Labels: size/xl

#191 fix(helm): add loki variables to admin-api
  helm/kai/templates/engine/admin-api/configmap.yaml
Labels: size/xs

#193 feat(helm): update mongo
  scripts/helmfile/helmfile.yaml
  scripts/helmfile/values/mongodb-database/values.yaml.gotmpl
Labels: size/xs

#196 fix(k8s-manager): add configurable kaniko image
  engine/k8s-manager/internal/infrastructure/config/viper.go
  engine/k8s-manager/internal/infrastructure/kube/registry/registry.go
  engine/k8s-manager/internal/infrastructure/kube/registry/registry_test.go
  engine/k8s-manager/internal/infrastructure/kube/registry/testdata/BuildImage_Job.golden
  helm/kai/CHART.md
  helm/kai/templates/engine/k8s-manager/configmap.yaml
  helm/kai/values.yaml
Labels: size/s

#185 feature(k8s-manager): parse logs correctly from fluent bit to loki
  engine/k8s-manager/config.yml
  engine/k8s-manager/internal/infrastructure/config/viper.go
  engine/k8s-manager/internal/infrastructure/kube/configuration/configmap.go
  engine/k8s-manager/internal/infrastructure/kube/configuration/testdata/ConfigMapCreation.golden
  engine/k8s-manager/internal/infrastructure/kube/process/containers.go
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithCPU.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithEnableGpu.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithHPA_Deployment.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithMoreReplicas.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithNetworking.golden
Labels: size/m

#197 feat(helm): add prometheus config to scrape kai telegraf metrics
  helm/kai/CHART.md
  helm/kai/templates/_helpers.tpl
  helm/kai/templates/engine/prometheus/additional-scrape-configs.yaml
  helm/kai/values.yaml
Labels: size/s

#198 feat: upload images to .kai subfolder
  engine/admin-api/adapter/repository/objectstorage/minio.go
  engine/admin-api/adapter/repository/objectstorage/minio_test.go
  engine/k8s-manager/internal/infrastructure/kube/registry/registry.go
  engine/k8s-manager/internal/infrastructure/kube/registry/testdata/BuildImage_Job.golden
Labels: size/s

#194 feat(k8s-manager): add telegraf instances as sidecar into the process pods
  engine/k8s-manager/internal/infrastructure/config/viper.go
  engine/k8s-manager/internal/infrastructure/kube/configuration/configmap.go
  engine/k8s-manager/internal/infrastructure/kube/configuration/testdata/ConfigMapCreation.golden
  engine/k8s-manager/internal/infrastructure/kube/network/create.go
  engine/k8s-manager/internal/infrastructure/kube/network/testdata/CreateNetwork.golden
  engine/k8s-manager/internal/infrastructure/kube/process/containers.go
  engine/k8s-manager/internal/infrastructure/kube/process/create.go
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithCPU.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithEnableGpu.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithHPA_Deployment.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithMoreReplicas.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithNetworking.golden
  engine/k8s-manager/internal/infrastructure/kube/process/volumes.go
Labels: size/m

#202 Deprecate mongo writer
  .ci/utils/publish.sh
  .github/images/kai-architecture.jpg
  .github/images/kai-architecture.png
  .github/workflows/build-images.yaml
  .github/workflows/test-release.yaml
  README.md
  engine/mongo-writer/.golangci.yml
  engine/mongo-writer/Dockerfile
  engine/mongo-writer/README.md
  engine/mongo-writer/cmd/main.go
  engine/mongo-writer/cmd/writer.go
  engine/mongo-writer/config.yml
  engine/mongo-writer/go.mod
  engine/mongo-writer/go.sum
  engine/mongo-writer/internal/compression/compression.go
  engine/mongo-writer/internal/config/config.go
  engine/mongo-writer/internal/logging/interface.go
  engine/mongo-writer/internal/logging/logger.go
  engine/mongo-writer/internal/logging/mock_helpers.go
  engine/mongo-writer/internal/logging/mocks_interface.go
  engine/mongo-writer/internal/mongodb/interface.go
  engine/mongo-writer/internal/mongodb/mocks_interface.go
  engine/mongo-writer/internal/mongodb/mongodb.go
  engine/mongo-writer/internal/nats/interface.go
  engine/mongo-writer/internal/nats/mocks_interface.go
  engine/mongo-writer/internal/nats/nats.go
  engine/mongo-writer/internal/parser/fluent.go
  engine/mongo-writer/internal/parser/fluent_test.go
  engine/mongo-writer/internal/parser/interface.go
  engine/mongo-writer/internal/parser/mocks_interface.go
  engine/mongo-writer/internal/processor/data_processor.go
  engine/mongo-writer/internal/processor/log_processor_test.go
  engine/mongo-writer/internal/processor/logs_processor.go
  engine/mongo-writer/internal/processor/utils.go
  engine/mongo-writer/sonar-project.properties
  helm/kai/CHART.md
  helm/kai/templates/_helpers.tpl
  helm/kai/templates/engine/mongo-writer/configmap.yaml
  helm/kai/templates/engine/mongo-writer/deployment.yaml
  helm/kai/values.yaml
  scripts/go_tidy_modules.sh
  scripts/helmfile/values/kai-local/values.yaml.gotmpl
  scripts/kaictl/cmd_build.sh
Labels: size/xl

#201 feat(helm): cleanup chart's unused components
  engine/admin-api/config.yml
  helm/kai/CHART.md
  helm/kai/Chart.lock
  helm/kai/Chart.yaml
  helm/kai/README.md
  helm/kai/templates/_helpers.tpl
  helm/kai/templates/admin-api/admin-api-pvc.yaml
  helm/kai/templates/admin-api/configmap.yaml
  helm/kai/templates/admin-api/deployment.yaml
  helm/kai/templates/admin-api/ingress.yaml
  helm/kai/templates/admin-api/service.yaml
  helm/kai/templates/engine/chronograf/config.yml
  helm/kai/templates/engine/chronograf/deployment.yml
  helm/kai/templates/engine/chronograf/pvc.yml
  helm/kai/templates/engine/chronograf/service.yml
  helm/kai/templates/grafana/datasources-configmap.yaml
  helm/kai/templates/k8s-manager/configmap.yaml
  helm/kai/templates/k8s-manager/deployment.yaml
  helm/kai/templates/k8s-manager/role.yaml
  helm/kai/templates/k8s-manager/role_binding.yaml
  helm/kai/templates/k8s-manager/service.yaml
  helm/kai/templates/k8s-manager/serviceaccount.yaml
  helm/kai/templates/keycloak/configmap.yaml
  helm/kai/templates/keycloak/deployment.yaml
  helm/kai/templates/keycloak/ingress.yaml
  helm/kai/templates/keycloak/kongplugin.yaml
  helm/kai/templates/keycloak/realm-init-secret.yaml
  helm/kai/templates/keycloak/secret.yaml
  helm/kai/templates/keycloak/service.yaml
  helm/kai/templates/keycloak/serviceaccount.yaml
  helm/kai/templates/minio-config/minio-config-job.yaml
  helm/kai/templates/minio-config/minio-config-secret.yaml
  helm/kai/templates/mongo-express/configmap.yaml
  helm/kai/templates/mongo-express/deployment.yml
  helm/kai/templates/mongo-express/service.yaml
  helm/kai/templates/nats-manager/configmap.yaml
  helm/kai/templates/nats-manager/deployment.yaml
  helm/kai/templates/nats-manager/service.yaml
  helm/kai/templates/nats/configmap.yaml
  helm/kai/templates/nats/service.yaml
  helm/kai/templates/nats/statefulset.yaml
  helm/kai/templates/prometheus/additional-scrape-configs.yaml
  helm/kai/templates/redis/redis-secret.yaml
  helm/kai/templates/registry/config-secret.yaml
  helm/kai/templates/registry/deployment.yaml
  helm/kai/templates/registry/htpasswd-secret.yaml
  helm/kai/templates/registry/ingress.yaml
  helm/kai/templates/registry/pvc.yaml
  helm/kai/templates/registry/registry-auth-secret.yaml
  helm/kai/templates/registry/service.yaml
  helm/kai/templates/registry/serviceaccount.yaml
  helm/kai/values.yaml
  scripts/helmfile/values/kai-local/values.yaml.gotmpl
  scripts/helmfile/values/mongodb-database/values.yaml.gotmpl
  scripts/kaictl/cmd_delete.sh
  scripts/kaictl/cmd_deploy.sh
  scripts/kaictl/cmd_minikube.sh
Labels: size/l

#206 feat(helm): add redis datasource to grafana
  helm/kai/CHART.md
  helm/kai/templates/_helpers.tpl
  helm/kai/templates/admin-api/deployment.yaml
  helm/kai/templates/grafana/datasources-configmap.yaml
  helm/kai/templates/redis/redis-secret.yaml
  helm/kai/templates/redis/redis-stack-master-config.yaml
  helm/kai/templates/redis/redis-stack-replicas-config.yaml
  helm/kai/values.yaml
Labels: size/m

#208 fix(helm): keycloak db credentials
  helm/kai/templates/keycloak/secret.yaml
Labels: size/xs

#209 fix(helm): remove repeated values for nats
  helm/kai/CHART.md
  helm/kai/values.yaml
Labels: size/s

#199 feat: add redis prediction database
  engine/admin-api/adapter/config/viper.go
  engine/admin-api/adapter/repository/redis/prediction.go
  engine/admin-api/adapter/repository/redis/prediction_test.go
  engine/admin-api/adapter/repository/redis/testdata/redis.conf
  engine/admin-api/adapter/service/proto/versionpb/version.pb.go
  engine/admin-api/adapter/service/versionservice/mapper.go
  engine/admin-api/adapter/service/versionservice/start_test.go
  engine/admin-api/adapter/service/versionservice/version_service.go
  engine/admin-api/domain/entity/product.go
  engine/admin-api/domain/repository/prediction.go
  engine/admin-api/domain/usecase/product_interactor.go
  engine/admin-api/domain/usecase/product_interactor_test.go
  engine/admin-api/go.mod
  engine/admin-api/go.sum
  engine/admin-api/main.go
  engine/admin-api/mocks/prediction_repo.go
  engine/admin-api/testhelpers/product_builder.go
  engine/admin-api/testhelpers/workflow_builder.go
  engine/k8s-manager/internal/application/service/container.go
  engine/k8s-manager/internal/application/usecase/interfaces.go
  engine/k8s-manager/internal/application/usecase/starter.go
  engine/k8s-manager/internal/application/usecase/starter_test.go
  engine/k8s-manager/internal/domain/version.go
  engine/k8s-manager/internal/domain/workflow.go
  engine/k8s-manager/internal/infrastructure/config/viper.go
  engine/k8s-manager/internal/infrastructure/grpc/mapper.go
  engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version.pb.go
  engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version.proto
  engine/k8s-manager/internal/infrastructure/grpc/version.go
  engine/k8s-manager/internal/infrastructure/grpc/version_test.go
  engine/k8s-manager/internal/infrastructure/kube/configuration/configmap.go
  engine/k8s-manager/internal/infrastructure/kube/configuration/create.go
  engine/k8s-manager/internal/infrastructure/kube/configuration/create_test.go
  engine/k8s-manager/internal/infrastructure/kube/configuration/testdata/ConfigMapCreation.golden
  engine/k8s-manager/internal/infrastructure/kube/configuration/types.go
  engine/k8s-manager/internal/infrastructure/kube/process/wait_processes.go
  engine/k8s-manager/internal/infrastructure/kube/service.go
  engine/k8s-manager/internal/testhelpers/version_builder.go
  engine/k8s-manager/internal/testhelpers/workflow_builder.go
  engine/k8s-manager/mocks/container_service_mock.go
  engine/k8s-manager/mocks/version_service_mock.go
  helm/kai/CHART.md
  helm/kai/templates/_helpers.tpl
  helm/kai/templates/grafana/datasources-configmap.yaml
  helm/kai/templates/k8s-manager/configmap.yaml
  helm/kai/templates/k8s-manager/deployment.yaml
  helm/kai/values.yaml
Labels: size/xl

#210 feat(workflows): update CHART.md docs with the new updated component versions
  .ci/utils/bump_version.sh
  .ci/utils/helm_docs.sh
  .github/workflows/test-release.yaml
Labels: size/s
