Repository konstellation-io/kai, pull requests merged in 2023-12, with the labels that each got.

#211 fix(k8s-manager): get tls secret name from env vars
  engine/k8s-manager/internal/infrastructure/config/viper.go
  engine/k8s-manager/internal/infrastructure/kube/network/publish.go
  engine/k8s-manager/internal/infrastructure/kube/network/publish_test.go
  engine/k8s-manager/internal/infrastructure/kube/network/testdata/PublishNetwork_GRPCTrigger.golden
Labels: size/s

#212 fix(admin-api): update config and logger management
  engine/admin-api/adapter/casbinauth/casbin_access_control.go
  engine/admin-api/adapter/casbinauth/casbin_test.go
  engine/admin-api/adapter/casbinauth/check_product_grants_test.go
  engine/admin-api/adapter/casbinauth/check_role_grants_test.go
  engine/admin-api/adapter/config/config.go
  engine/admin-api/adapter/config/viper.go
  engine/admin-api/adapter/config/viper_test.go
  engine/admin-api/adapter/gql/http_handler.go
  engine/admin-api/adapter/gql/resolver.go
  engine/admin-api/adapter/repository/mongodb/connection.go
  engine/admin-api/adapter/repository/mongodb/processregistry/process_registry_repository_test.go
  engine/admin-api/adapter/repository/mongodb/processregistry/repository.go
  engine/admin-api/adapter/repository/mongodb/processrepository/process_repository_test.go
  engine/admin-api/adapter/repository/mongodb/processrepository/repository.go
  engine/admin-api/adapter/repository/mongodb/user_activity.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/repository.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/version_repository_test.go
  engine/admin-api/adapter/service/loki/client.go
  engine/admin-api/adapter/service/loki/client_test.go
  engine/admin-api/adapter/service/natsmanager/nats_manager.go
  engine/admin-api/adapter/service/natsmanager/nats_manager_test.go
  engine/admin-api/adapter/service/user/keycloak_integration_test.go
  engine/admin-api/adapter/service/versionservice/start_test.go
  engine/admin-api/adapter/service/versionservice/stop_test.go
  engine/admin-api/adapter/service/versionservice/version_service.go
  engine/admin-api/adapter/service/versionservice/version_service_test.go
  engine/admin-api/config.yml
  engine/admin-api/delivery/http/controller/graphql.go
  engine/admin-api/delivery/http/middleware/auth.go
  engine/admin-api/delivery/http/middleware/operation.go
  engine/admin-api/delivery/http/server.go
  engine/admin-api/delivery/http/server_test.go
  engine/admin-api/domain/service/logging/interface.go
  engine/admin-api/domain/service/logging/logger.go
  engine/admin-api/domain/usecase/user.go
  engine/admin-api/domain/usecase/user_test.go
  engine/admin-api/main.go
  engine/admin-api/mocks/helpers.go
  engine/admin-api/mocks/logging_interface.go
  helm/kai/templates/admin-api/configmap.yaml
Labels: size/l

#214 fix(admin-api): delete published version on unpublish action
  engine/admin-api/domain/usecase/version/unpublish.go
  engine/admin-api/domain/usecase/version/unpublish_test.go
Labels: size/s

#226 Feature (admin-api): bind version, change get version
  engine/admin-api/adapter/gql/generated.go
  engine/admin-api/adapter/gql/resolver.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/repository.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/version_repository_test.go
  engine/admin-api/domain/repository/version.go
  engine/admin-api/domain/usecase/version/get_latest.go
  engine/admin-api/domain/usecase/version/get_latest_test.go
  engine/admin-api/mocks/prediction_repo.go
  engine/admin-api/mocks/repo_version.go
  engine/admin-api/schema.graphql
Labels: size/xl
