Repository konstellation-io/kai, pull requests merged in 2023-10, with the labels that each got.

#119 fix: deprecate krt-files-downloader
  engine/k8s-manager/config.yml
  engine/k8s-manager/internal/infrastructure/kube/configuration/create.go
  engine/k8s-manager/internal/infrastructure/kube/process/containers.go
  engine/k8s-manager/internal/infrastructure/kube/process/create.go
  engine/k8s-manager/internal/infrastructure/kube/process/downloader.go
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithCPU.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithEnableGpu.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithMemory.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithMoreReplicas.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithNetwork.golden
  engine/k8s-manager/internal/infrastructure/kube/process/testdata/StartProcess_WithNetworking.golden
  engine/k8s-manager/internal/infrastructure/kube/process/volumes.go
  helm/kai/CHART.md
  helm/kai/templates/engine/k8s-manager/configmap.yaml
  helm/kai/values.yaml
  kaictl.sh
  scripts/kaictl/cmd_build.sh
Labels: size/xl

#128 feat: create minio bucket
  helm/kai/CHART.md
  helm/kai/templates/engine/admin-api/configmap.yaml
  helm/kai/values.yaml
Labels: size/s

#129 feat(admin-api): upgrade krt library
  engine/admin-api/go.mod
  engine/admin-api/go.sum
Labels: size/xs

#126 feature: create s3 folders on product creation
  engine/admin-api/.mockery.yaml
  engine/admin-api/adapter/config/viper.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/version_repository_test.go
  engine/admin-api/adapter/repository/objectstorage/client.go
  engine/admin-api/adapter/repository/objectstorage/s3.go
  engine/admin-api/adapter/repository/objectstorage/s3_test.go
  engine/admin-api/domain/repository/object_storage.go
  engine/admin-api/domain/usecase/product_interactor.go
  engine/admin-api/domain/usecase/product_interactor_test.go
  engine/admin-api/domain/usecase/server_info_test.go
  engine/admin-api/go.mod
  engine/admin-api/go.sum
  engine/admin-api/main.go
  engine/admin-api/mocks/object_storage.go
  helm/kai/templates/engine/admin-api/configmap.yaml
  helm/kai/templates/engine/admin-api/secret.yaml
Labels: size/m

#127 feat(k8s-manager): enable TLS on trigger publication
  engine/k8s-manager/internal/infrastructure/config/viper.go
  engine/k8s-manager/internal/infrastructure/kube/network/publish.go
  engine/k8s-manager/internal/infrastructure/kube/network/publish_test.go
  helm/kai/CHART.md
  helm/kai/templates/engine/k8s-manager/configmap.yaml
  helm/kai/values.yaml
Labels: size/m

#131 ci: fix Nyx commit message regex expressions
  .nyx.yaml
Labels: size/s

#132 feat(admin-api): allow override latest version of registered processes
  engine/admin-api/domain/usecase/process_service.go
  engine/admin-api/domain/usecase/process_service_test.go
  engine/admin-api/testhelpers/registered_process_builder.go
Labels: size/m

#130 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/s

#133 fix(helmfile): refactor helmfile definition to support new versions
  scripts/helmfile/helmfile.yaml
Labels: size/xs

#135 fix(helm): process registry pvc storage class cannot be set
  helm/kai/CHART.md
  helm/kai/templates/engine/registry/pvc.yaml
  helm/kai/values.yaml
Labels: size/s

#136 feat: initialize nats centralized configuration on version start
  engine/admin-api/adapter/service/natsmanager/global_kv_store.go
  engine/admin-api/adapter/service/natsmanager/global_kv_store_test.go
  engine/admin-api/adapter/service/natsmanager/mapper.go
  engine/admin-api/adapter/service/natsmanager/nats_manager.go
  engine/admin-api/adapter/service/natsmanager/nats_manager_test.go
  engine/admin-api/adapter/service/natsmanager/update_kv_configuration.go
  engine/admin-api/adapter/service/natsmanager/update_kv_configuration_test.go
  engine/admin-api/adapter/service/proto/natspb/nats.pb.go
  engine/admin-api/adapter/service/proto/natspb/nats_grpc.pb.go
  engine/admin-api/adapter/service/versionservice/mapper.go
  engine/admin-api/adapter/service/versionservice/start_test.go
  engine/admin-api/adapter/service/versionservice/version_service.go
  engine/admin-api/domain/entity/key_value_configuration.go
  engine/admin-api/domain/entity/key_value_store.go
  engine/admin-api/domain/entity/key_value_store_config.go
  engine/admin-api/domain/entity/object_store_config.go
  engine/admin-api/domain/entity/stream_info.go
  engine/admin-api/domain/entity/version_config.go
  engine/admin-api/domain/entity/version_config_test.go
  engine/admin-api/domain/service/nats.go
  engine/admin-api/domain/service/version.go
  engine/admin-api/domain/usecase/product_interactor.go
  engine/admin-api/domain/usecase/version/start.go
  engine/admin-api/domain/usecase/version/start_test.go
  engine/admin-api/main.go
  engine/admin-api/mocks/nats_manager.go
  engine/admin-api/mocks/service_nats.go
  engine/admin-api/mocks/service_version.go
  engine/admin-api/testhelpers/version_builder.go
  engine/admin-api/testhelpers/workflow_builder.go
  engine/nats-manager/go.mod
  engine/nats-manager/go.sum
  engine/nats-manager/internal/entity/key_value_config.go
  engine/nats-manager/internal/entity/key_value_store.go
  engine/nats-manager/internal/interfaces/nats_client.go
  engine/nats-manager/internal/interfaces/nats_manager.go
  engine/nats-manager/internal/manager/create_kv_store.go
  engine/nats-manager/internal/manager/create_kv_stores_test.go
  engine/nats-manager/internal/manager/nats.go
  engine/nats-manager/internal/manager/update_configuration.go
  engine/nats-manager/internal/manager/update_configuration_test.go
  engine/nats-manager/internal/service/mapper.go
  engine/nats-manager/internal/service/nats.go
  engine/nats-manager/internal/service/nats_test.go
  engine/nats-manager/mocks/nats_client.go
  engine/nats-manager/mocks/nats_manager.go
  engine/nats-manager/nats/client.go
  engine/nats-manager/nats/update_configuration.go
  engine/nats-manager/nats/update_configuration_test.go
  engine/nats-manager/proto/natspb/nats.pb.go
  engine/nats-manager/proto/natspb/nats.proto
  engine/nats-manager/proto/natspb/nats_grpc.pb.go
Labels: size/xl

#140 Add a default ttl for Object Stores
  .kaictl.conf
  engine/nats-manager/cmd/main.go
  engine/nats-manager/go.mod
  engine/nats-manager/go.sum
  engine/nats-manager/internal/config/config.go
  engine/nats-manager/internal/service/nats.go
  engine/nats-manager/internal/service/nats_test.go
  engine/nats-manager/nats/client.go
  helm/kai/templates/engine/nats-manager/configmap.yaml
  helm/kai/templates/engine/nats-manager/deployment.yaml
  scripts/helmfile/values/kai-local/values.yaml.gotmpl
  scripts/kaictl/cmd_deploy.sh
Labels: size/l

#143 feat(helm): add minio tier configuration process
  helm/kai/CHART.md
  helm/kai/templates/_helpers.tpl
  helm/kai/templates/engine/admin-api/configmap.yaml
  helm/kai/templates/engine/admin-api/deployment.yaml
  helm/kai/templates/engine/admin-api/minio-config-job.yaml
  helm/kai/templates/engine/admin-api/minio-config-secret.yaml
  helm/kai/values.yaml
  scripts/helmfile/values/kai-local/values.yaml.gotmpl
Labels: size/m

#144 fix: fix alias setting on nats-manager configuration
  engine/nats-manager/internal/config/config.go
Labels: size/xs

#145 Fix env variable reading
  engine/nats-manager/internal/config/config.go
Labels: size/xs

#148 fix env variable reading
  engine/nats-manager/internal/config/config.go
  engine/nats-manager/out.yaml
Labels: size/s

#150 fix(helm): minio tier config secret
  helm/kai/templates/engine/admin-api/minio-config-secret.yaml
  scripts/helmfile/values/kai-local/values.yaml.gotmpl
Labels: size/xs

#149 feat(helm): enable minio console
  helm/kai/CHART.md
  helm/kai/values.yaml
  scripts/kaictl/cmd_etchost.sh
Labels: size/s

#153 feat: global tls config
  helm/kai/CHART.md
  helm/kai/templates/engine/admin-api/configmap.yaml
  helm/kai/templates/engine/admin-api/ingress.yaml
  helm/kai/templates/engine/k8s-manager/configmap.yaml
  helm/kai/templates/engine/keycloak/ingress.yaml
  helm/kai/templates/engine/keycloak/kongplugin.yaml
  helm/kai/templates/engine/registry/ingress.yaml
  helm/kai/templates/engine/registry/registry-auth-secret.yaml
  helm/kai/values.yaml
  scripts/helmfile/values/kai-local/values.yaml.gotmpl
Labels: size/m

#151 feat(helm): minio OIDC
  helm/kai/CHART.md
  helm/kai/Chart.lock
  helm/kai/Chart.yaml
  helm/kai/templates/engine/admin-api/minio-config-job.yaml
  helm/kai/templates/engine/keycloak/realm-init-secret.yaml
  helm/kai/templates/engine/minio-config/minio-config-job.yaml
  helm/kai/templates/engine/minio-config/minio-config-secret.yaml
  helm/kai/values.yaml
  scripts/helmfile/values/kai-local/values.yaml.gotmpl
Labels: size/m

#158 fix: inject global key value store config
  engine/admin-api/adapter/service/natsmanager/mapper.go
  engine/admin-api/adapter/service/natsmanager/nats_manager_test.go
  engine/admin-api/adapter/service/proto/versionpb/version.pb.go
  engine/admin-api/adapter/service/proto/versionpb/version_grpc.pb.go
  engine/admin-api/adapter/service/versionservice/start_test.go
  engine/admin-api/adapter/service/versionservice/version_service.go
  engine/admin-api/domain/entity/key_value_store.go
  engine/admin-api/domain/entity/product.go
  engine/admin-api/domain/entity/version_config_test.go
  engine/admin-api/domain/usecase/product_interactor.go
  engine/admin-api/domain/usecase/product_interactor_test.go
  engine/admin-api/domain/usecase/version/start.go
  engine/admin-api/domain/usecase/version/start_test.go
  engine/k8s-manager/internal/domain/version.go
  engine/k8s-manager/internal/infrastructure/grpc/mapper.go
  engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version.pb.go
  engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version.proto
  engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version_grpc.pb.go
  engine/k8s-manager/internal/infrastructure/grpc/version_test.go
  engine/k8s-manager/internal/infrastructure/kube/configuration/create.go
  engine/k8s-manager/internal/infrastructure/kube/configuration/testdata/ConfigMapCreation.golden
  engine/k8s-manager/internal/infrastructure/kube/configuration/types.go
  engine/k8s-manager/internal/testhelpers/version_builder.go
Labels: size/l

#161 chore: increase kong's proxy buffers size in local env
  helm/kai/CHART.md
  scripts/helmfile/values/kong/values.yaml
Labels: size/s

#160 feat(helm): add loki-stack to KAI chart
  helm/kai/CHART.md
  helm/kai/Chart.lock
  helm/kai/Chart.yaml
  helm/kai/templates/engine/admin-api/configmap.yaml
  helm/kai/values.yaml
  scripts/kaictl/cmd_etchost.sh
Labels: size/m

#159 fix(helm): Keycloak minio oidc client configuration
  helm/kai/templates/engine/keycloak/minio-client-config-job.yaml
  helm/kai/templates/engine/keycloak/realm-init-secret.yaml
  helm/kai/templates/engine/minio-config/minio-config-job.yaml
Labels: size/m
