Repository konstellation-io/kai, pull requests merged in 2023-06, with the labels that each got.

#55 refactor (admin-api): deprecate doc generator
  engine/admin-api/adapter/gql/generated.go
  engine/admin-api/adapter/repository/mongodb/version.go
  engine/admin-api/adapter/version/doc_generator.go
  engine/admin-api/adapter/version/doc_generator_test.go
  engine/admin-api/domain/entity/version.go
  engine/admin-api/domain/repository/version.go
  engine/admin-api/domain/usecase/version/doc_generator.go
  engine/admin-api/domain/usecase/version_dashboards_test.go
  engine/admin-api/domain/usecase/version_interactor.go
  engine/admin-api/domain/usecase/version_interactor_test.go
  engine/admin-api/go.mod
  engine/admin-api/go.sum
  engine/admin-api/main.go
  engine/admin-api/mocks/repo_version.go
  engine/admin-api/mocks/version_doc_generator.go
  engine/admin-api/schema.graphql
Labels: size/m

#56 Feat/keycloak
  .kaictl.conf
  engine/admin-api/.golangci.yml
  engine/admin-api/adapter/auth/casbin_access_control.go
  engine/admin-api/adapter/auth/casbin_test.go
  engine/admin-api/adapter/auth/errors.go
  engine/admin-api/adapter/config/config.go
  engine/admin-api/adapter/service/keycloak.go
  engine/admin-api/adapter/service/keycloak_integration_test.go
  engine/admin-api/domain/usecase/auth/access_control.go
  engine/admin-api/domain/usecase/user.go
  engine/admin-api/domain/usecase/user_activity.go
  engine/admin-api/domain/usecase/user_test.go
  engine/admin-api/main.go
  engine/admin-api/mocks/auth_access_control.go
  engine/nats-manager/go.mod
  engine/nats-manager/go.sum
  go.work.sum
  helm/kai/templates/_helpers.tpl
  helm/kai/templates/engine/admin-api/configmap.yaml
  helm/kai/templates/engine/admin-api/deployment.yaml
  helm/kai/templates/engine/admin-api/ingress.yaml
  helm/kai/templates/engine/keycloak/configmap.yaml
  helm/kai/templates/engine/keycloak/deployment.yaml
  helm/kai/templates/engine/keycloak/ingress.yaml
  helm/kai/templates/engine/keycloak/kongplugin.yaml
  helm/kai/templates/engine/keycloak/realm-init-secret.yaml
  helm/kai/templates/engine/keycloak/secret.yaml
  helm/kai/templates/engine/keycloak/service.yaml
  helm/kai/templates/engine/keycloak/serviceaccount.yaml
  helm/kai/values.yaml
  scripts/helmfile/helmfile.lock
  scripts/helmfile/helmfile.yaml
  scripts/helmfile/values/kai-local/values.yaml.gotmpl
  scripts/helmfile/values/kong/values.yaml
  scripts/helmfile/values/postgres-database/values.yaml
  scripts/kaictl/cmd_deploy.sh
  scripts/kaictl/cmd_etchost.sh
  scripts/kaictl/cmd_minikube.sh
Labels: size/xl

#58 ci: add new release workflow
  .ci/CHANGELOG.tpl
  .ci/utils/publish.sh
  .ci/utils/release_chart.sh
  .github/workflows/test-admin-api.yaml
  .github/workflows/test-k8s-manager.yaml
  .github/workflows/test-mongo-writer.yaml
  .github/workflows/test-nats-manager.yaml
  .github/workflows/test-release.yaml
  .gitignore
  .nyx.yaml
  engine/k8s-manager/.golangci.yml
  engine/mongo-writer/.golangci.yml
Labels: size/l

#59 ci: fix protected branches permissions
  .github/workflows/test-release.yaml
Labels: size/s

#61 ci: fix sonar artifact generation and download
  .github/workflows/test-release.yaml
Labels: size/s
