Repository konstellation-io/kai, pull requests merged in 2023-07, with the labels that each got.

#64 feat: add process registry
  helm/kai/CHART.md
  helm/kai/templates/_helpers.tpl
  helm/kai/templates/engine/registry/deployment.yaml
  helm/kai/templates/engine/registry/ingress.yaml
  helm/kai/templates/engine/registry/pvc.yaml
  helm/kai/templates/engine/registry/secret.yaml
  helm/kai/templates/engine/registry/service.yaml
  helm/kai/templates/engine/registry/serviceaccount.yaml
  helm/kai/values.yaml
  scripts/helmfile/helmfile.lock
  scripts/kaictl/cmd_etchost.sh
Labels: size/m

#69 chore: set latest tags for local deployment images
  scripts/helmfile/values/kai-local/values.yaml.gotmpl
Labels: size/s

#72 ci: fix Test and Release workflow triggers
  .github/workflows/test-release.yaml
  helm/kai/CHART.md
Labels: size/s

#71 fix: remove registry ingress
  helm/kai/CHART.md
  helm/kai/templates/engine/registry/ingress.yaml
  helm/kai/values.yaml
  scripts/helmfile/helmfile.lock
  scripts/kaictl/cmd_etchost.sh
Labels: size/m

#75 refactor: add gitlint pre-commit hook
  .gitlint
  .pre-commit-config.yaml
  README.md
Labels: size/s

#76 fix error handling on version create
  engine/admin-api/adapter/gql/resolver.go
  engine/admin-api/domain/usecase/version_interactor.go
Labels: size/s

#77 avoid build deprecated runners
  scripts/kaictl/cmd_build.sh
Labels: size/xs

#78 fix: rename k8s-manager env vars prefix from kre to kai
  helm/kai/templates/engine/k8s-manager/configmap.yaml
Labels: size/s

#81 feat: Deprecate go work sum github ref
  .gitignore
  go.work
  go.work.sum
Labels: size/m

#82 Feature/knt1 376 get server info
  engine/admin-api/adapter/auth/casbin_test.go
  engine/admin-api/adapter/auth/errors.go
  engine/admin-api/adapter/casbinauth/casbin_access_control.go
  engine/admin-api/adapter/casbinauth/casbin_test.go
  engine/admin-api/adapter/casbinauth/check_product_grants_test.go
  engine/admin-api/adapter/casbinauth/check_role_grants_test.go
  engine/admin-api/adapter/casbinauth/errors.go
  engine/admin-api/adapter/config/viper.go
  engine/admin-api/adapter/gql/generated.go
  engine/admin-api/adapter/gql/http_handler.go
  engine/admin-api/adapter/gql/resolver.go
  engine/admin-api/casbin_rbac_model.conf
  engine/admin-api/casbin_rbac_policy.csv
  engine/admin-api/config.yml
  engine/admin-api/delivery/http/controller/graphql.go
  engine/admin-api/delivery/http/middleware/auth.go
  engine/admin-api/delivery/http/middleware/operation.go
  engine/admin-api/delivery/http/server.go
  engine/admin-api/domain/entity/server_info.go
  engine/admin-api/domain/usecase/auth/access_control.go
  engine/admin-api/domain/usecase/auth/errors.go
  engine/admin-api/domain/usecase/auth/errors_test.go
  engine/admin-api/domain/usecase/errors/errors.go
  engine/admin-api/domain/usecase/product_interactor.go
  engine/admin-api/domain/usecase/product_interactor_test.go
  engine/admin-api/domain/usecase/server_info.go
  engine/admin-api/domain/usecase/server_info_test.go
  engine/admin-api/domain/usecase/testdata/versions.yaml
  engine/admin-api/domain/usecase/user.go
  engine/admin-api/domain/usecase/user_activity.go
  engine/admin-api/domain/usecase/user_test.go
  engine/admin-api/domain/usecase/version_dashboards.go
  engine/admin-api/domain/usecase/version_interactor_test.go
  engine/admin-api/go.mod
  engine/admin-api/go.sum
  engine/admin-api/gqlgen.yml
  engine/admin-api/graphql.http
  engine/admin-api/main.go
  engine/admin-api/mocks/auth_access_control.go
  engine/admin-api/schema.graphql
  engine/admin-api/tools.go
  engine/admin-api/versions.yaml
Labels: size/xl

#83 docs: fix outdated link and add missing requirements
  README.md
Labels: size/xs

#85 feat: add resource limits struct
  engine/admin-api/adapter/repository/mongodb/version/entity.go
  engine/admin-api/adapter/repository/mongodb/version/mapper.go
  engine/admin-api/adapter/repository/mongodb/version/mapper_test.go
  engine/admin-api/adapter/service/k8smanager/mapper.go
  engine/admin-api/adapter/service/k8smanager/start_test.go
  engine/admin-api/adapter/service/proto/versionpb/version.pb.go
  engine/admin-api/adapter/service/proto/versionpb/version_grpc.pb.go
  engine/admin-api/domain/entity/version.go
  engine/admin-api/domain/usecase/krt/krt_mapper.go
  engine/admin-api/domain/usecase/krt/krt_mapper_test.go
  engine/admin-api/go.mod
  engine/admin-api/go.sum
  engine/admin-api/testdata/classificator_krt.yaml
  engine/admin-api/testhelpers/process_builder.go
  engine/k8s-manager/internal/application/usecase/starter_test.go
  engine/k8s-manager/internal/domain/process.go
  engine/k8s-manager/internal/infrastructure/grpc/mapper.go
  engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version.pb.go
  engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version.proto
  engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version_grpc.pb.go
  engine/k8s-manager/internal/infrastructure/grpc/version_test.go
  engine/k8s-manager/internal/infrastructure/kube/process/containers.go
  engine/k8s-manager/internal/infrastructure/kube/process/create_test.go
  engine/k8s-manager/internal/testhelpers/process_builder.go
Labels: size/xl
