Repository konstellation-io/kai, pull requests merged in 2024-01, with the labels that each got.

#217 feat(admin-api): create a global repository for shared processes on the process registry so that they can be listed from any product
  engine/admin-api/adapter/config/viper.go
  engine/admin-api/adapter/gql/generated.go
  engine/admin-api/adapter/gql/http_handler.go
  engine/admin-api/adapter/gql/models.go
  engine/admin-api/adapter/gql/resolver.go
  engine/admin-api/adapter/repository/mongodb/processregistry/entity.go
  engine/admin-api/adapter/repository/mongodb/processregistry/mapper.go
  engine/admin-api/adapter/repository/mongodb/processregistry/mapper_test.go
  engine/admin-api/adapter/repository/mongodb/processregistry/process_registry_repository_test.go
  engine/admin-api/adapter/repository/mongodb/processregistry/repository.go
  engine/admin-api/adapter/repository/mongodb/processrepository/entity.go
  engine/admin-api/adapter/repository/mongodb/processrepository/mapper.go
  engine/admin-api/adapter/repository/mongodb/processrepository/process_repository_test.go
  engine/admin-api/adapter/repository/mongodb/processrepository/repository.go
  engine/admin-api/casbin_rbac_policy.csv
  engine/admin-api/delivery/http/controller/graphql.go
  engine/admin-api/domain/entity/process.go
  engine/admin-api/domain/entity/process_registry.go
  engine/admin-api/domain/entity/process_test.go
  engine/admin-api/domain/entity/registered_process.go
  engine/admin-api/domain/entity/version.go
  engine/admin-api/domain/mocks/logs_logs.go
  engine/admin-api/domain/repository/process_registry.go
  engine/admin-api/domain/repository/process_repository.go
  engine/admin-api/domain/service/auth/access_control.go
  engine/admin-api/domain/usecase/logs/logs.go
  engine/admin-api/domain/usecase/process/process_service.go
  engine/admin-api/domain/usecase/process/process_service_test.go
  engine/admin-api/domain/usecase/process/register.go
  engine/admin-api/domain/usecase/process/register_test.go
  engine/admin-api/domain/usecase/process/search.go
  engine/admin-api/domain/usecase/process/search_test.go
  engine/admin-api/domain/usecase/process/testdata/fake_compressed_process.txt
  engine/admin-api/domain/usecase/process_service.go
  engine/admin-api/domain/usecase/process_service_test.go
  engine/admin-api/domain/usecase/testdata/fake_compressed_process.txt
  engine/admin-api/gqlgen.yml
  engine/admin-api/main.go
  engine/admin-api/mocks/object_storage.go
  engine/admin-api/mocks/prediction_repo.go
  engine/admin-api/mocks/repo_process_registry.go
  engine/admin-api/mocks/repo_process_repository.go
  engine/admin-api/schema.graphql
  engine/admin-api/testhelpers/registered_process_builder.go
Labels: size/xl

#228 Feat/helm add kai kli ci OIDC client
  helm/kai/CHART.md
  helm/kai/templates/keycloak/realm-init-secret.yaml
  helm/kai/values.yaml
  scripts/helmfile/values/kai-local/values.yaml.gotmpl
Labels: size/s

#229 fix(nats-manager): delete simplelogger
  engine/nats-manager/cmd/main.go
  engine/nats-manager/go.mod
  engine/nats-manager/go.sum
  engine/nats-manager/internal/logger/interface.go
  engine/nats-manager/internal/logging/interface.go
  engine/nats-manager/internal/manager/create_kv_stores.go
  engine/nats-manager/internal/manager/create_kv_stores_test.go
  engine/nats-manager/internal/manager/create_object_store_test.go
  engine/nats-manager/internal/manager/create_streams_test.go
  engine/nats-manager/internal/manager/delete_kv_stores_test.go
  engine/nats-manager/internal/manager/delete_object_stores_test.go
  engine/nats-manager/internal/manager/delete_streams_test.go
  engine/nats-manager/internal/manager/nats.go
  engine/nats-manager/internal/manager/update_configuration_test.go
  engine/nats-manager/internal/service/nats.go
  engine/nats-manager/internal/service/nats_test.go
  engine/nats-manager/mocks/helpers.go
  engine/nats-manager/mocks/logging_interface.go
  engine/nats-manager/nats/client.go
  engine/nats-manager/nats/client_integration_test.go
  engine/nats-manager/nats/update_configuration.go
  libs/simplelogger/go.mod
  libs/simplelogger/simplelogger.go
  libs/simplelogger/simplelogger_test.go
  scripts/go_tidy_modules.sh
Labels: size/l

#231 fix: missing tags
  engine/admin-api/domain/service/auth/errors_test.go
  engine/nats-manager/internal/manager/update_configuration_test.go
Labels: size/xs

#232 feat: add missing service accounts and imagePullSecrets to the chart
  helm/kai/CHART.md
  helm/kai/templates/_helpers.tpl
  helm/kai/templates/admin-api/deployment.yaml
  helm/kai/templates/admin-api/serviceaccount.yaml
  helm/kai/templates/k8s-manager/deployment.yaml
  helm/kai/templates/nats-manager/deployment.yaml
  helm/kai/templates/nats-manager/serviceaccount.yaml
  helm/kai/templates/nats/configmap.yaml
  helm/kai/templates/nats/service.yaml
  helm/kai/templates/nats/serviceaccount.yaml
  helm/kai/templates/nats/statefulset.yaml
  helm/kai/values.yaml
Labels: size/m

#235 Update develop
  .github/workflows/test-release.yaml
  RELEASE_NOTES.md
  helm/kai/CHART.md
  helm/kai/Chart.yaml
  helm/kai/values.yaml
Labels: size/s

#237 Fix/ci test and release triggers
  .github/workflows/test-release.yaml
Labels: size/s

#238 fix: Nats Manager imagePullSecrets
  helm/kai/templates/nats-manager/deployment.yaml
Labels: size/xs

#239 feat: add the option to deploy new versions with 0 downtime admin api
  engine/admin-api/adapter/gql/generated.go
  engine/admin-api/adapter/gql/models.go
  engine/admin-api/adapter/gql/resolver.go
  engine/admin-api/adapter/service/versionservice/version_service_test.go
  engine/admin-api/domain/entity/version.go
  engine/admin-api/domain/usecase/version/errors.go
  engine/admin-api/domain/usecase/version/publish.go
  engine/admin-api/domain/usecase/version/publish_test.go
  engine/admin-api/domain/usecase/version/start.go
  engine/admin-api/domain/usecase/version/start_test.go
  engine/admin-api/domain/usecase/version/unpublish_test.go
  engine/admin-api/schema.graphql
  engine/k8s-manager/internal/infrastructure/grpc/version.go
  engine/k8s-manager/internal/infrastructure/kube/network/publish.go
  engine/k8s-manager/internal/infrastructure/kube/network/suite_test.go
  engine/k8s-manager/internal/infrastructure/kube/network/testdata/PublishNetwork.golden
  engine/k8s-manager/internal/infrastructure/kube/network/testdata/PublishNetwork_GRPCTrigger.golden
  engine/k8s-manager/internal/infrastructure/kube/network/testdata/PublishNetwork_WithTLS.golden
  engine/k8s-manager/internal/infrastructure/kube/network/testdata/PublishNetwork_WithTLS_WithTLSSecret.golden
Labels: size/l

#241 feat(admin-api): ensure kai bucket creation
  engine/admin-api/adapter/service/user/group_exists.go
  engine/admin-api/adapter/service/user/group_exists_test.go
  engine/admin-api/adapter/service/user/keycloak.go
  engine/admin-api/main.go
Labels: size/m

#240 Add netrc secret to kaniko for building process images
  engine/k8s-manager/internal/infrastructure/config/viper.go
  engine/k8s-manager/internal/infrastructure/kube/registry/registry.go
  engine/k8s-manager/internal/infrastructure/kube/registry/registry_test.go
  engine/k8s-manager/internal/infrastructure/kube/registry/testdata/BuildImage_Job_NetrcEnabled.golden
  helm/kai/templates/_helpers.tpl
  helm/kai/templates/k8s-manager/configmap.yaml
  helm/kai/templates/k8s-manager/netrc-secret.yaml
  helm/kai/values.yaml
Labels: size/m
