Repository konstellation-io/kai, pull requests merged in 2024-02, with the labels that each got.

#243 fix(admin-api): update echo
  engine/admin-api/delivery/http/controller/graphql.go
  engine/admin-api/delivery/http/httperrors/errors.go
  engine/admin-api/delivery/http/middleware/auth.go
  engine/admin-api/delivery/http/middleware/operation.go
  engine/admin-api/delivery/http/server.go
  engine/admin-api/go.mod
  engine/admin-api/go.sum
  engine/admin-api/mocks/controller_graphql.go
Labels: size/s

#242 feat: get version published networks
  engine/admin-api/adapter/gql/generated.go
  engine/admin-api/adapter/gql/models.go
  engine/admin-api/adapter/gql/resolver.go
  engine/admin-api/adapter/service/proto/versionpb/version.pb.go
  engine/admin-api/adapter/service/proto/versionpb/version_grpc.pb.go
  engine/admin-api/adapter/service/versionservice/mapper.go
  engine/admin-api/adapter/service/versionservice/version_service.go
  engine/admin-api/adapter/service/versionservice/version_service_test.go
  engine/admin-api/domain/entity/version.go
  engine/admin-api/domain/service/version.go
  engine/admin-api/domain/usecase/version/get_by_tag.go
  engine/admin-api/domain/usecase/version/get_by_tag_test.go
  engine/admin-api/domain/usecase/version/publish_test.go
  engine/admin-api/domain/usecase/version/start_test.go
  engine/admin-api/domain/usecase/version/stop_test.go
  engine/admin-api/domain/usecase/version/suite_test.go
  engine/admin-api/domain/usecase/version/unpublish_test.go
  engine/admin-api/mocks/service_version.go
  engine/admin-api/mocks/version_service.go
  engine/admin-api/schema.graphql
  engine/k8s-manager/internal/application/service/container.go
  engine/k8s-manager/internal/application/usecase/interfaces.go
  engine/k8s-manager/internal/application/usecase/publisher.go
  engine/k8s-manager/internal/application/usecase/starter_test.go
  engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version.pb.go
  engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version.proto
  engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version_grpc.pb.go
  engine/k8s-manager/internal/infrastructure/grpc/version.go
  engine/k8s-manager/internal/infrastructure/grpc/version_test.go
  engine/k8s-manager/internal/infrastructure/kube/network/publish_test.go
  engine/k8s-manager/internal/infrastructure/kube/network/published_triggers.go
  engine/k8s-manager/internal/infrastructure/kube/network/published_triggers_test.go
  engine/k8s-manager/internal/infrastructure/kube/network/suite_test.go
  engine/k8s-manager/internal/infrastructure/kube/service.go
  engine/k8s-manager/internal/testhelpers/process_builder.go
  engine/k8s-manager/mocks/container_service_mock.go
  engine/k8s-manager/mocks/version_service_mock.go
Labels: size/xl

#244 feat: rollback product creation if fails
  engine/admin-api/adapter/repository/mongodb/product.go
  engine/admin-api/adapter/repository/mongodb/product_test.go
  engine/admin-api/adapter/repository/objectstorage/minio.go
  engine/admin-api/adapter/repository/objectstorage/minio_test.go
  engine/admin-api/adapter/repository/redis/prediction.go
  engine/admin-api/adapter/repository/redis/prediction_test.go
  engine/admin-api/adapter/service/natsmanager/global_kv_store.go
  engine/admin-api/adapter/service/natsmanager/global_kv_store_test.go
  engine/admin-api/adapter/service/proto/natspb/nats.pb.go
  engine/admin-api/adapter/service/proto/natspb/nats_grpc.pb.go
  engine/admin-api/adapter/service/user/delete_group.go
  engine/admin-api/adapter/service/user/delete_group_test.go
  engine/admin-api/adapter/service/user/delete_user.go
  engine/admin-api/adapter/service/user/delete_user_test.go
  engine/admin-api/adapter/service/user/keycloak_integration_test.go
  engine/admin-api/domain/repository/object_storage.go
  engine/admin-api/domain/repository/prediction.go
  engine/admin-api/domain/repository/product.go
  engine/admin-api/domain/service/nats.go
  engine/admin-api/domain/service/user_registry.go
  engine/admin-api/domain/usecase/product_interactor.go
  engine/admin-api/domain/usecase/product_interactor_test.go
  engine/admin-api/mocks/nats_manager.go
  engine/admin-api/mocks/object_storage.go
  engine/admin-api/mocks/prediction_repo.go
  engine/admin-api/mocks/repo_product.go
  engine/admin-api/mocks/service_nats.go
  engine/admin-api/mocks/service_user_registry.go
  engine/admin-api/testhelpers/product_builder.go
  engine/nats-manager/internal/interfaces/nats_manager.go
  engine/nats-manager/internal/manager/delete_kv_stores.go
  engine/nats-manager/internal/manager/delete_kv_stores_test.go
  engine/nats-manager/internal/service/nats.go
  engine/nats-manager/internal/service/nats_test.go
  engine/nats-manager/mocks/nats_manager.go
  engine/nats-manager/proto/natspb/nats.pb.go
  engine/nats-manager/proto/natspb/nats.proto
  engine/nats-manager/proto/natspb/nats_grpc.pb.go
Labels: size/xl

#247 fix(k8s-manager): make log level configurable and set default to info
  engine/k8s-manager/internal/infrastructure/config/viper.go
  helm/kai/CHART.md
  helm/kai/templates/k8s-manager/configmap.yaml
  helm/kai/values.yaml
Labels: size/xs

#246 feat: add node selectors to processes
  engine/admin-api/adapter/repository/mongodb/versionrepository/entity.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/mapper.go
  engine/admin-api/adapter/service/proto/versionpb/version.pb.go
  engine/admin-api/adapter/service/versionservice/mapper.go
  engine/admin-api/domain/entity/process.go
  engine/admin-api/domain/usecase/process/register.go
  engine/admin-api/domain/usecase/version/create.go
  engine/admin-api/domain/usecase/version/krt_mapper.go
  engine/admin-api/go.mod
  engine/admin-api/go.sum
  engine/k8s-manager/internal/domain/process.go
  engine/k8s-manager/internal/infrastructure/grpc/mapper.go
  engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version.pb.go
  engine/k8s-manager/internal/infrastructure/grpc/proto/versionpb/version.proto
  engine/k8s-manager/internal/infrastructure/kube/process/capabilities.go
  engine/k8s-manager/internal/infrastructure/kube/process/create.go
Labels: size/l

#248 Feature: Delete process registry endpoint
  engine/admin-api/adapter/config/viper.go
  engine/admin-api/adapter/gql/generated.go
  engine/admin-api/adapter/gql/http_handler.go
  engine/admin-api/adapter/gql/models.go
  engine/admin-api/adapter/gql/resolver.go
  engine/admin-api/adapter/repository/mongodb/processrepository/process_repository_test.go
  engine/admin-api/adapter/repository/mongodb/processrepository/repository.go
  engine/admin-api/adapter/repository/mongodb/versionrepository/version_repository_test.go
  engine/admin-api/adapter/service/loki/client_test.go
  engine/admin-api/adapter/service/registry/process_registry.go
  engine/admin-api/adapter/service/registry/process_registry_test.go
  engine/admin-api/casbin_rbac_policy.csv
  engine/admin-api/delivery/http/controller/graphql.go
  engine/admin-api/domain/repository/process_repository.go
  engine/admin-api/domain/service/auth/access_control.go
  engine/admin-api/domain/service/registry.go
  engine/admin-api/domain/usecase/process/delete.go
  engine/admin-api/domain/usecase/process/delete_test.go
  engine/admin-api/domain/usecase/process/handler.go
  engine/admin-api/domain/usecase/process/handler_test.go
  engine/admin-api/domain/usecase/process/process_service.go
  engine/admin-api/domain/usecase/process/register.go
  engine/admin-api/domain/usecase/process/register_test.go
  engine/admin-api/domain/usecase/process/search.go
  engine/admin-api/domain/usecase/process/search_test.go
  engine/admin-api/go.sum
  engine/admin-api/main.go
  engine/admin-api/mocks/object_storage.go
  engine/admin-api/mocks/prediction_repo.go
  engine/admin-api/mocks/repo_process_repository.go
  engine/admin-api/mocks/service_registry.go
  engine/admin-api/schema.graphql
  helm/kai/CHART.md
  helm/kai/templates/_helpers.tpl
  helm/kai/templates/admin-api/configmap.yaml
  helm/kai/templates/admin-api/deployment.yaml
  helm/kai/templates/admin-api/secret.yaml
  helm/kai/templates/registry/deployment.yaml
  scripts/kaictl/cmd_deploy.sh
Labels: size/xl

#249 fix: wrong links
  README.md
Labels: size/s

#251 Bugfix/update readme diagram
  .github/images/kai-architecture.png
  README.md
Labels: size/s

#254 feat: update go version to 1.22
  .github/workflows/ci-merge-develop-from-main.yaml
  .github/workflows/test-release.yaml
  engine/admin-api/Dockerfile
  engine/admin-api/adapter/gql/generated.go
  engine/admin-api/adapter/gql/models.go
  engine/admin-api/go.mod
  engine/admin-api/go.sum
  engine/admin-api/mocks/object_storage.go
  engine/admin-api/mocks/prediction_repo.go
  engine/k8s-manager/Dockerfile
  engine/k8s-manager/go.mod
  engine/k8s-manager/go.sum
  engine/nats-manager/Dockerfile
  engine/nats-manager/go.mod
  engine/nats-manager/go.sum
Labels: size/m

#255 core: increase refresh token duration
  helm/kai/CHART.md
  helm/kai/templates/keycloak/realm-init-secret.yaml
  helm/kai/values.yaml
Labels: size/xs

#256 fix: check grants process registry ls and check if product exists
  engine/admin-api/casbin_rbac_policy.csv
  engine/admin-api/domain/service/auth/access_control.go
  engine/admin-api/domain/usecase/process/handler.go
  engine/admin-api/domain/usecase/process/handler_test.go
  engine/admin-api/domain/usecase/process/search.go
  engine/admin-api/domain/usecase/process/search_test.go
  engine/admin-api/main.go
  engine/admin-api/sonar-project.properties
Labels: size/s

#252 fix: return error if process image id is too long
  engine/admin-api/domain/usecase/process/handler_test.go
  engine/admin-api/domain/usecase/process/register.go
  engine/admin-api/domain/usecase/process/register_test.go
  engine/admin-api/domain/usecase/process/search_test.go
  engine/admin-api/go.mod
  engine/admin-api/go.sum
  engine/admin-api/testhelpers/product_builder.go
Labels: size/m

#260 fix(admin-api): remove volumes and init containers
  helm/kai/templates/admin-api/admin-api-pvc.yaml
  helm/kai/templates/admin-api/configmap.yaml
  helm/kai/templates/admin-api/deployment.yaml
  helm/kai/values.yaml
Labels: size/s

#261 feat(helm): allow set deployment strategies
  helm/kai/templates/admin-api/deployment.yaml
  helm/kai/templates/k8s-manager/deployment.yaml
  helm/kai/templates/keycloak/deployment.yaml
  helm/kai/templates/nats-manager/deployment.yaml
  helm/kai/templates/registry/deployment.yaml
  helm/kai/values.yaml
Labels: size/s

#265 feat(helm): add registry storage driver config
  helm/kai/CHART.md
  helm/kai/templates/registry/config-secret.yaml
  helm/kai/values.yaml
Labels: size/s

#264 feat: add grants management
  engine/admin-api/adapter/casbinauth/check_role_grants_test.go
  engine/admin-api/adapter/gql/generated.go
  engine/admin-api/adapter/gql/http_handler.go
  engine/admin-api/adapter/gql/models.go
  engine/admin-api/adapter/gql/resolver.go
  engine/admin-api/adapter/repository/mongodb/product.go
  engine/admin-api/adapter/repository/mongodb/product_test.go
  engine/admin-api/adapter/service/user/add_product_grants.go
  engine/admin-api/adapter/service/user/add_product_grants_test.go
  engine/admin-api/adapter/service/user/keycloak.go
  engine/admin-api/adapter/service/user/keycloak_integration_test.go
  engine/admin-api/adapter/service/user/revoke_product_grants.go
  engine/admin-api/adapter/service/user/revoke_product_grants_test.go
  engine/admin-api/casbin_rbac_policy.csv
  engine/admin-api/delivery/http/controller/graphql.go
  engine/admin-api/domain/repository/product.go
  engine/admin-api/domain/service/auth/access_control.go
  engine/admin-api/domain/service/user_registry.go
  engine/admin-api/domain/usecase/process/delete.go
  engine/admin-api/domain/usecase/process/delete_test.go
  engine/admin-api/domain/usecase/process/search.go
  engine/admin-api/domain/usecase/process/search_test.go
  engine/admin-api/domain/usecase/product_interactor.go
  engine/admin-api/domain/usecase/product_interactor_test.go
  engine/admin-api/domain/usecase/user.go
  engine/admin-api/domain/usecase/user_activity.go
  engine/admin-api/domain/usecase/user_activity_test.go
  engine/admin-api/domain/usecase/user_test.go
  engine/admin-api/domain/usecase/version/create.go
  engine/admin-api/domain/usecase/version/create_test.go
  engine/admin-api/domain/usecase/version/get_by_tag.go
  engine/admin-api/domain/usecase/version/get_by_tag_test.go
  engine/admin-api/domain/usecase/version/publish.go
  engine/admin-api/domain/usecase/version/publish_test.go
  engine/admin-api/domain/usecase/version/start.go
  engine/admin-api/domain/usecase/version/start_test.go
  engine/admin-api/domain/usecase/version/stop.go
  engine/admin-api/domain/usecase/version/stop_test.go
  engine/admin-api/domain/usecase/version/unpublish.go
  engine/admin-api/domain/usecase/version/unpublish_test.go
  engine/admin-api/main.go
  engine/admin-api/mocks/object_storage.go
  engine/admin-api/mocks/prediction_repo.go
  engine/admin-api/mocks/repo_product.go
  engine/admin-api/mocks/service_user_registry.go
  engine/admin-api/mocks/usecase_user_activity.go
  engine/admin-api/schema.graphql
Labels: size/xl

#268 fix(helm): add missing resources blocks and pod scheduling options
  helm/kai/CHART.md
  helm/kai/templates/admin-api/deployment.yaml
  helm/kai/templates/k8s-manager/deployment.yaml
  helm/kai/templates/nats-manager/deployment.yaml
  helm/kai/templates/nats/statefulset.yaml
  helm/kai/values.yaml
Labels: size/s

#269 feat: add custom errors to get product version
  engine/admin-api/domain/usecase/version/errors.go
  engine/admin-api/domain/usecase/version/get_by_tag.go
  engine/admin-api/domain/usecase/version/get_by_tag_test.go
  engine/admin-api/domain/usecase/version/get_latest.go
  engine/admin-api/domain/usecase/version/get_latest_test.go
Labels: size/m

#267 fix: product register check if product exists
  engine/admin-api/domain/usecase/process/register.go
  engine/admin-api/domain/usecase/process/register_test.go
Labels: size/s
